# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_POUET(object):
    def setupUi(self, POUET):
        POUET.setObjectName("POUET")
        POUET.resize(1368, 1008)
        self.allSkyUpdateValue = QtWidgets.QLabel(POUET)
        self.allSkyUpdateValue.setGeometry(QtCore.QRect(1230, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.allSkyUpdateValue.setFont(font)
        self.allSkyUpdateValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allSkyUpdateValue.setObjectName("allSkyUpdateValue")
        self.label_13 = QtWidgets.QLabel(POUET)
        self.label_13.setGeometry(QtCore.QRect(900, 10, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.allSkyframe = QtWidgets.QFrame(POUET)
        self.allSkyframe.setGeometry(QtCore.QRect(900, 40, 461, 461))
        self.allSkyframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.allSkyframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.allSkyframe.setObjectName("allSkyframe")
        self.allSkyView = QtWidgets.QGraphicsView(self.allSkyframe)
        self.allSkyView.setGeometry(QtCore.QRect(0, 0, 461, 461))
        self.allSkyView.setObjectName("allSkyView")
        self.label = QtWidgets.QLabel(POUET)
        self.label.setGeometry(QtCore.QRect(20, 10, 131, 31))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.configTime = QtWidgets.QDateTimeEdit(POUET)
        self.configTime.setGeometry(QtCore.QRect(150, 10, 161, 27))
        self.configTime.setAutoFillBackground(False)
        self.configTime.setCalendarPopup(True)
        self.configTime.setObjectName("configTime")
        self.label_14 = QtWidgets.QLabel(POUET)
        self.label_14.setGeometry(QtCore.QRect(900, 510, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.frame_2 = QtWidgets.QFrame(POUET)
        self.frame_2.setGeometry(QtCore.QRect(900, 540, 461, 461))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.visibility_airmass = QtWidgets.QDoubleSpinBox(POUET)
        self.visibility_airmass.setGeometry(QtCore.QRect(1040, 510, 51, 27))
        self.visibility_airmass.setDecimals(1)
        self.visibility_airmass.setMinimum(0.1)
        self.visibility_airmass.setMaximum(4.0)
        self.visibility_airmass.setSingleStep(0.1)
        self.visibility_airmass.setProperty("value", 1.5)
        self.visibility_airmass.setObjectName("visibility_airmass")
        self.label_15 = QtWidgets.QLabel(POUET)
        self.label_15.setGeometry(QtCore.QRect(980, 510, 61, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(POUET)
        self.label_16.setGeometry(QtCore.QRect(1100, 510, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.visibility_moon_angle = QtWidgets.QSpinBox(POUET)
        self.visibility_moon_angle.setGeometry(QtCore.QRect(1230, 510, 48, 27))
        self.visibility_moon_angle.setMaximum(180)
        self.visibility_moon_angle.setProperty("value", 90)
        self.visibility_moon_angle.setObjectName("visibility_moon_angle")
        self.visibility_plot = QtWidgets.QPushButton(POUET)
        self.visibility_plot.setGeometry(QtCore.QRect(1290, 510, 71, 27))
        self.visibility_plot.setObjectName("visibility_plot")
        self.tabWidget = QtWidgets.QTabWidget(POUET)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 871, 951))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.obs = QtWidgets.QWidget()
        self.obs.setObjectName("obs")
        self.retrieveObs = QtWidgets.QPushButton(self.obs)
        self.retrieveObs.setGeometry(QtCore.QRect(10, 13, 141, 23))
        self.retrieveObs.setObjectName("retrieveObs")
        self.listObs = QtWidgets.QTableView(self.obs)
        self.listObs.setGeometry(QtCore.QRect(10, 50, 841, 861))
        self.listObs.setDragEnabled(True)
        self.listObs.setAlternatingRowColors(True)
        self.listObs.setShowGrid(True)
        self.listObs.setGridStyle(QtCore.Qt.DashLine)
        self.listObs.setSortingEnabled(True)
        self.listObs.setObjectName("listObs")
        self.checkObsStatus = QtWidgets.QPushButton(self.obs)
        self.checkObsStatus.setGeometry(QtCore.QRect(170, 13, 141, 23))
        self.checkObsStatus.setObjectName("checkObsStatus")
        self.tabWidget.addTab(self.obs, "")
        self.program = QtWidgets.QWidget()
        self.program.setObjectName("program")
        self.label_27 = QtWidgets.QLabel(self.program)
        self.label_27.setGeometry(QtCore.QRect(190, 150, 541, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.tabWidget.addTab(self.program, "")
        self.weather = QtWidgets.QWidget()
        self.weather.setObjectName("weather")
        self.weatherRefresh = QtWidgets.QPushButton(self.weather)
        self.weatherRefresh.setGeometry(QtCore.QRect(20, 500, 111, 27))
        self.weatherRefresh.setObjectName("weatherRefresh")
        self.weatherHumidityValue = QtWidgets.QLabel(self.weather)
        self.weatherHumidityValue.setGeometry(QtCore.QRect(150, 470, 41, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherHumidityValue.setFont(font)
        self.weatherHumidityValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherHumidityValue.setObjectName("weatherHumidityValue")
        self.weatherWindSpeedValue = QtWidgets.QLabel(self.weather)
        self.weatherWindSpeedValue.setGeometry(QtCore.QRect(150, 380, 41, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherWindSpeedValue.setFont(font)
        self.weatherWindSpeedValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherWindSpeedValue.setObjectName("weatherWindSpeedValue")
        self.weatherTemperatureValue = QtWidgets.QLabel(self.weather)
        self.weatherTemperatureValue.setGeometry(QtCore.QRect(150, 440, 41, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherTemperatureValue.setFont(font)
        self.weatherTemperatureValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherTemperatureValue.setObjectName("weatherTemperatureValue")
        self.weatherLastUpdate = QtWidgets.QLabel(self.weather)
        self.weatherLastUpdate.setGeometry(QtCore.QRect(230, 350, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.weatherLastUpdate.setFont(font)
        self.weatherLastUpdate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weatherLastUpdate.setObjectName("weatherLastUpdate")
        self.weatherConditions = QtWidgets.QLabel(self.weather)
        self.weatherConditions.setGeometry(QtCore.QRect(20, 350, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.weatherConditions.setFont(font)
        self.weatherConditions.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherConditions.setObjectName("weatherConditions")
        self.weatherWindDirectionValue = QtWidgets.QLabel(self.weather)
        self.weatherWindDirectionValue.setGeometry(QtCore.QRect(150, 410, 41, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherWindDirectionValue.setFont(font)
        self.weatherWindDirectionValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherWindDirectionValue.setObjectName("weatherWindDirectionValue")
        self.weatherWindSpeed = QtWidgets.QLabel(self.weather)
        self.weatherWindSpeed.setGeometry(QtCore.QRect(20, 380, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherWindSpeed.setFont(font)
        self.weatherWindSpeed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherWindSpeed.setObjectName("weatherWindSpeed")
        self.weatherWindDirection = QtWidgets.QLabel(self.weather)
        self.weatherWindDirection.setGeometry(QtCore.QRect(20, 410, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherWindDirection.setFont(font)
        self.weatherWindDirection.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherWindDirection.setObjectName("weatherWindDirection")
        self.weatherTemperature = QtWidgets.QLabel(self.weather)
        self.weatherTemperature.setGeometry(QtCore.QRect(20, 440, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherTemperature.setFont(font)
        self.weatherTemperature.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherTemperature.setObjectName("weatherTemperature")
        self.weatherHumidity = QtWidgets.QLabel(self.weather)
        self.weatherHumidity.setGeometry(QtCore.QRect(20, 470, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherHumidity.setFont(font)
        self.weatherHumidity.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherHumidity.setObjectName("weatherHumidity")
        self.weatherLastUpdateValue = QtWidgets.QLabel(self.weather)
        self.weatherLastUpdateValue.setGeometry(QtCore.QRect(310, 350, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.weatherLastUpdateValue.setFont(font)
        self.weatherLastUpdateValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weatherLastUpdateValue.setObjectName("weatherLastUpdateValue")
        self.siteLabel = QtWidgets.QLabel(self.weather)
        self.siteLabel.setGeometry(QtCore.QRect(20, 10, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.siteLabel.setFont(font)
        self.siteLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.siteLabel.setObjectName("siteLabel")
        self.sitePositionValue = QtWidgets.QLabel(self.weather)
        self.sitePositionValue.setGeometry(QtCore.QRect(150, 40, 181, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sitePositionValue.setFont(font)
        self.sitePositionValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sitePositionValue.setObjectName("sitePositionValue")
        self.sitePosition = QtWidgets.QLabel(self.weather)
        self.sitePosition.setGeometry(QtCore.QRect(20, 40, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sitePosition.setFont(font)
        self.sitePosition.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sitePosition.setObjectName("sitePosition")
        self.nightLabel = QtWidgets.QLabel(self.weather)
        self.nightLabel.setGeometry(QtCore.QRect(20, 90, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nightLabel.setFont(font)
        self.nightLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightLabel.setObjectName("nightLabel")
        self.nightStartCivilValue = QtWidgets.QLabel(self.weather)
        self.nightStartCivilValue.setGeometry(QtCore.QRect(150, 120, 181, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightStartCivilValue.setFont(font)
        self.nightStartCivilValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightStartCivilValue.setObjectName("nightStartCivilValue")
        self.nightStartCivil = QtWidgets.QLabel(self.weather)
        self.nightStartCivil.setGeometry(QtCore.QRect(20, 120, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightStartCivil.setFont(font)
        self.nightStartCivil.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightStartCivil.setObjectName("nightStartCivil")
        self.nightEndCivilValue = QtWidgets.QLabel(self.weather)
        self.nightEndCivilValue.setGeometry(QtCore.QRect(520, 120, 181, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightEndCivilValue.setFont(font)
        self.nightEndCivilValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightEndCivilValue.setObjectName("nightEndCivilValue")
        self.nightEndCivil = QtWidgets.QLabel(self.weather)
        self.nightEndCivil.setGeometry(QtCore.QRect(390, 120, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightEndCivil.setFont(font)
        self.nightEndCivil.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightEndCivil.setObjectName("nightEndCivil")
        self.nightStartNauticalValue = QtWidgets.QLabel(self.weather)
        self.nightStartNauticalValue.setGeometry(QtCore.QRect(150, 150, 181, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightStartNauticalValue.setFont(font)
        self.nightStartNauticalValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightStartNauticalValue.setObjectName("nightStartNauticalValue")
        self.nightEndNauticalValue = QtWidgets.QLabel(self.weather)
        self.nightEndNauticalValue.setGeometry(QtCore.QRect(520, 150, 181, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightEndNauticalValue.setFont(font)
        self.nightEndNauticalValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightEndNauticalValue.setObjectName("nightEndNauticalValue")
        self.nightStartNautical = QtWidgets.QLabel(self.weather)
        self.nightStartNautical.setGeometry(QtCore.QRect(20, 150, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightStartNautical.setFont(font)
        self.nightStartNautical.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightStartNautical.setObjectName("nightStartNautical")
        self.nightEndNautical = QtWidgets.QLabel(self.weather)
        self.nightEndNautical.setGeometry(QtCore.QRect(390, 150, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightEndNautical.setFont(font)
        self.nightEndNautical.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightEndNautical.setObjectName("nightEndNautical")
        self.nightStartAstroValue = QtWidgets.QLabel(self.weather)
        self.nightStartAstroValue.setGeometry(QtCore.QRect(150, 180, 181, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightStartAstroValue.setFont(font)
        self.nightStartAstroValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightStartAstroValue.setObjectName("nightStartAstroValue")
        self.nightStartAstro = QtWidgets.QLabel(self.weather)
        self.nightStartAstro.setGeometry(QtCore.QRect(20, 180, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightStartAstro.setFont(font)
        self.nightStartAstro.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightStartAstro.setObjectName("nightStartAstro")
        self.nightEndAstro = QtWidgets.QLabel(self.weather)
        self.nightEndAstro.setGeometry(QtCore.QRect(390, 180, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightEndAstro.setFont(font)
        self.nightEndAstro.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightEndAstro.setObjectName("nightEndAstro")
        self.nightEndAstroValue = QtWidgets.QLabel(self.weather)
        self.nightEndAstroValue.setGeometry(QtCore.QRect(520, 180, 181, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightEndAstroValue.setFont(font)
        self.nightEndAstroValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightEndAstroValue.setObjectName("nightEndAstroValue")
        self.sunLabel = QtWidgets.QLabel(self.weather)
        self.sunLabel.setGeometry(QtCore.QRect(20, 230, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sunLabel.setFont(font)
        self.sunLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sunLabel.setObjectName("sunLabel")
        self.sunCoordinatesValues = QtWidgets.QLabel(self.weather)
        self.sunCoordinatesValues.setGeometry(QtCore.QRect(150, 260, 181, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sunCoordinatesValues.setFont(font)
        self.sunCoordinatesValues.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sunCoordinatesValues.setObjectName("sunCoordinatesValues")
        self.sunCoordinates = QtWidgets.QLabel(self.weather)
        self.sunCoordinates.setGeometry(QtCore.QRect(20, 260, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sunCoordinates.setFont(font)
        self.sunCoordinates.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sunCoordinates.setObjectName("sunCoordinates")
        self.sunAltaz = QtWidgets.QLabel(self.weather)
        self.sunAltaz.setGeometry(QtCore.QRect(20, 290, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sunAltaz.setFont(font)
        self.sunAltaz.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sunAltaz.setObjectName("sunAltaz")
        self.sunAltazValue = QtWidgets.QLabel(self.weather)
        self.sunAltazValue.setGeometry(QtCore.QRect(150, 290, 181, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sunAltazValue.setFont(font)
        self.sunAltazValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sunAltazValue.setObjectName("sunAltazValue")
        self.line_8 = QtWidgets.QFrame(self.weather)
        self.line_8.setGeometry(QtCore.QRect(20, 70, 821, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.weather)
        self.line_9.setGeometry(QtCore.QRect(20, 210, 821, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.weather)
        self.line_10.setGeometry(QtCore.QRect(20, 320, 821, 16))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.tabWidget.addTab(self.weather, "")
        self.config = QtWidgets.QWidget()
        self.config.setObjectName("config")
        self.config_clouds_analyse = QtWidgets.QCheckBox(self.config)
        self.config_clouds_analyse.setGeometry(QtCore.QRect(10, 120, 131, 22))
        self.config_clouds_analyse.setChecked(True)
        self.config_clouds_analyse.setObjectName("config_clouds_analyse")
        self.config_wind_analyse = QtWidgets.QCheckBox(self.config)
        self.config_wind_analyse.setGeometry(QtCore.QRect(10, 150, 121, 22))
        self.config_wind_analyse.setChecked(True)
        self.config_wind_analyse.setObjectName("config_wind_analyse")
        self.label_18 = QtWidgets.QLabel(self.config)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.toolButton = QtWidgets.QToolButton(self.config)
        self.toolButton.setGeometry(QtCore.QRect(140, 40, 211, 25))
        self.toolButton.setObjectName("toolButton")
        self.label_19 = QtWidgets.QLabel(self.config)
        self.label_19.setGeometry(QtCore.QRect(10, 90, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.config)
        self.label_20.setGeometry(QtCore.QRect(10, 40, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.config_weather_update_every = QtWidgets.QSpinBox(self.config)
        self.config_weather_update_every.setGeometry(QtCore.QRect(170, 180, 48, 27))
        self.config_weather_update_every.setMaximum(30)
        self.config_weather_update_every.setProperty("value", 2)
        self.config_weather_update_every.setObjectName("config_weather_update_every")
        self.label_21 = QtWidgets.QLabel(self.config)
        self.label_21.setGeometry(QtCore.QRect(10, 180, 161, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.line_4 = QtWidgets.QFrame(self.config)
        self.line_4.setGeometry(QtCore.QRect(10, 70, 911, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.config_clouds_auto_update = QtWidgets.QCheckBox(self.config)
        self.config_clouds_auto_update.setGeometry(QtCore.QRect(180, 120, 211, 22))
        self.config_clouds_auto_update.setChecked(True)
        self.config_clouds_auto_update.setObjectName("config_clouds_auto_update")
        self.config_wind_auto_update = QtWidgets.QCheckBox(self.config)
        self.config_wind_auto_update.setGeometry(QtCore.QRect(180, 150, 211, 22))
        self.config_wind_auto_update.setChecked(True)
        self.config_wind_auto_update.setObjectName("config_wind_auto_update")
        self.line_5 = QtWidgets.QFrame(self.config)
        self.line_5.setGeometry(QtCore.QRect(10, 210, 911, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_22 = QtWidgets.QLabel(self.config)
        self.label_22.setGeometry(QtCore.QRect(10, 230, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.config_show_obs_visibility = QtWidgets.QCheckBox(self.config)
        self.config_show_obs_visibility.setGeometry(QtCore.QRect(10, 260, 411, 22))
        self.config_show_obs_visibility.setChecked(True)
        self.config_show_obs_visibility.setObjectName("config_show_obs_visibility")
        self.config_show_obs_allsky = QtWidgets.QCheckBox(self.config)
        self.config_show_obs_allsky.setGeometry(QtCore.QRect(10, 290, 411, 22))
        self.config_show_obs_allsky.setChecked(True)
        self.config_show_obs_allsky.setObjectName("config_show_obs_allsky")
        self.label_25 = QtWidgets.QLabel(self.config)
        self.label_25.setGeometry(QtCore.QRect(10, 890, 401, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.config)
        self.label_26.setGeometry(QtCore.QRect(470, 890, 391, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.tabWidget.addTab(self.config, "")
        self.log = QtWidgets.QWidget()
        self.log.setObjectName("log")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.log)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 841, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget.addTab(self.log, "")
        self.configUpdate = QtWidgets.QPushButton(POUET)
        self.configUpdate.setGeometry(QtCore.QRect(430, 10, 101, 27))
        self.configUpdate.setObjectName("configUpdate")
        self.allSkyRefresh = QtWidgets.QPushButton(POUET)
        self.allSkyRefresh.setGeometry(QtCore.QRect(1057, 7, 101, 27))
        self.allSkyRefresh.setObjectName("allSkyRefresh")
        self.allSkyUpdate = QtWidgets.QLabel(POUET)
        self.allSkyUpdate.setGeometry(QtCore.QRect(1158, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.allSkyUpdate.setFont(font)
        self.allSkyUpdate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allSkyUpdate.setObjectName("allSkyUpdate")
        self.statusFrame = QtWidgets.QFrame(POUET)
        self.statusFrame.setGeometry(QtCore.QRect(540, 10, 341, 61))
        self.statusFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.statusFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statusFrame.setObjectName("statusFrame")
        self.statusLabel = QtWidgets.QLabel(self.statusFrame)
        self.statusLabel.setGeometry(QtCore.QRect(6, 5, 331, 51))
        self.statusLabel.setObjectName("statusLabel")
        self.configTimenow = QtWidgets.QPushButton(POUET)
        self.configTimenow.setGeometry(QtCore.QRect(320, 10, 101, 27))
        self.configTimenow.setObjectName("configTimenow")

        self.retranslateUi(POUET)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(POUET)

    def retranslateUi(self, POUET):
        _translate = QtCore.QCoreApplication.translate
        POUET.setWindowTitle(_translate("POUET", "Pouet"))
        self.allSkyUpdateValue.setText(_translate("POUET", "XX.XX.XXZXX:XX:XX"))
        self.label_13.setText(_translate("POUET", "Current All Sky image"))
        self.label.setText(_translate("POUET", "Date & Time (UTC)"))
        self.configTime.setDisplayFormat(_translate("POUET", "dd.MM.yyyy HH:mm"))
        self.label_14.setText(_translate("POUET", "Visibility"))
        self.label_15.setText(_translate("POUET", "Airmass:"))
        self.label_16.setText(_translate("POUET", "Angle to Moon [°]:"))
        self.visibility_plot.setText(_translate("POUET", "Draw"))
        self.retrieveObs.setText(_translate("POUET", "Load observables list"))
        self.checkObsStatus.setText(_translate("POUET", "Load observables list"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.obs), _translate("POUET", "Observations"))
        self.label_27.setText(_translate("POUET", "Here we can select the programs we want to include"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.program), _translate("POUET", "Programs"))
        self.weatherRefresh.setText(_translate("POUET", "Refresh now"))
        self.weatherHumidityValue.setText(_translate("POUET", "XX.X"))
        self.weatherWindSpeedValue.setText(_translate("POUET", "XX.X"))
        self.weatherTemperatureValue.setText(_translate("POUET", "XX.X"))
        self.weatherLastUpdate.setText(_translate("POUET", "Last update: "))
        self.weatherConditions.setText(_translate("POUET", "Current weather conditions"))
        self.weatherWindDirectionValue.setText(_translate("POUET", "XX.X"))
        self.weatherWindSpeed.setText(_translate("POUET", "Wind speed [m/s]:"))
        self.weatherWindDirection.setText(_translate("POUET", "Wind direction [°]:"))
        self.weatherTemperature.setText(_translate("POUET", "Temperature [°C]:"))
        self.weatherHumidity.setText(_translate("POUET", "Humidity [%]:"))
        self.weatherLastUpdateValue.setText(_translate("POUET", " XX.XX.XXZXX:XX:XX"))
        self.siteLabel.setText(_translate("POUET", "Site"))
        self.sitePositionValue.setText(_translate("POUET", "XX.X"))
        self.sitePosition.setText(_translate("POUET", "Location:"))
        self.nightLabel.setText(_translate("POUET", "Night"))
        self.nightStartCivilValue.setText(_translate("POUET", "XX.X"))
        self.nightStartCivil.setText(_translate("POUET", "Start (civil):"))
        self.nightEndCivilValue.setText(_translate("POUET", "XX.X"))
        self.nightEndCivil.setText(_translate("POUET", "End (civil):"))
        self.nightStartNauticalValue.setText(_translate("POUET", "XX.X"))
        self.nightEndNauticalValue.setText(_translate("POUET", "XX.X"))
        self.nightStartNautical.setText(_translate("POUET", "Start (nautical):"))
        self.nightEndNautical.setText(_translate("POUET", "End (nautical):"))
        self.nightStartAstroValue.setText(_translate("POUET", "XX.X"))
        self.nightStartAstro.setText(_translate("POUET", "Start (astro):"))
        self.nightEndAstro.setText(_translate("POUET", "End (astro):"))
        self.nightEndAstroValue.setText(_translate("POUET", "XX.X"))
        self.sunLabel.setText(_translate("POUET", "Sun"))
        self.sunCoordinatesValues.setText(_translate("POUET", "XX.X"))
        self.sunCoordinates.setText(_translate("POUET", "Coordinates:"))
        self.sunAltaz.setText(_translate("POUET", "Alt [°]/Az [°]:"))
        self.sunAltazValue.setText(_translate("POUET", "XX.X"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.weather), _translate("POUET", "Site"))
        self.config_clouds_analyse.setText(_translate("POUET", "Analyse clouds"))
        self.config_wind_analyse.setText(_translate("POUET", "Analyse wind"))
        self.label_18.setText(_translate("POUET", "Observation site"))
        self.toolButton.setText(_translate("POUET", "Load configuration file"))
        self.label_19.setText(_translate("POUET", "Weather analysis"))
        self.label_20.setText(_translate("POUET", "La Silla"))
        self.label_21.setText(_translate("POUET", "Weather update [min]"))
        self.config_clouds_auto_update.setText(_translate("POUET", "Auto-refresh clouds"))
        self.config_wind_auto_update.setText(_translate("POUET", "Auto-refresh wind"))
        self.label_22.setText(_translate("POUET", "Observations"))
        self.config_show_obs_visibility.setText(_translate("POUET", "Show selected objects in visibility tool"))
        self.config_show_obs_allsky.setText(_translate("POUET", "Show selected objects in All Sky image"))
        self.label_25.setText(_translate("POUET", "Written by Thibault Kuntzer and Vivien Bonvin, 2015-2018"))
        self.label_26.setText(_translate("POUET", "https://github.com/vbonvin/POUET"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.config), _translate("POUET", "Configuration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log), _translate("POUET", "View logs"))
        self.configUpdate.setText(_translate("POUET", "Update"))
        self.allSkyRefresh.setText(_translate("POUET", "Refresh now"))
        self.allSkyUpdate.setText(_translate("POUET", "Last update: "))
        self.statusLabel.setText(_translate("POUET", "Current Status"))
        self.configTimenow.setText(_translate("POUET", "Set to now"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    POUET = QtWidgets.QDialog()
    ui = Ui_POUET()
    ui.setupUi(POUET)
    POUET.show()
    sys.exit(app.exec_())

