# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_POUET(object):
    def setupUi(self, POUET):
        POUET.setObjectName("POUET")
        POUET.resize(1368, 1008)
        self.label_12 = QtWidgets.QLabel(POUET)
        self.label_12.setGeometry(QtCore.QRect(1150, 10, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(POUET)
        self.label_13.setGeometry(QtCore.QRect(900, 10, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.frame = QtWidgets.QFrame(POUET)
        self.frame.setGeometry(QtCore.QRect(900, 40, 461, 461))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(POUET)
        self.label.setGeometry(QtCore.QRect(20, 10, 131, 31))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.config_time = QtWidgets.QDateTimeEdit(POUET)
        self.config_time.setGeometry(QtCore.QRect(150, 10, 161, 27))
        self.config_time.setAutoFillBackground(False)
        self.config_time.setCalendarPopup(True)
        self.config_time.setObjectName("config_time")
        self.label_14 = QtWidgets.QLabel(POUET)
        self.label_14.setGeometry(QtCore.QRect(900, 510, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.frame_2 = QtWidgets.QFrame(POUET)
        self.frame_2.setGeometry(QtCore.QRect(900, 540, 461, 461))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.visibility_airmass = QtWidgets.QDoubleSpinBox(POUET)
        self.visibility_airmass.setGeometry(QtCore.QRect(1040, 510, 51, 27))
        self.visibility_airmass.setDecimals(1)
        self.visibility_airmass.setMinimum(0.1)
        self.visibility_airmass.setMaximum(4.0)
        self.visibility_airmass.setSingleStep(0.1)
        self.visibility_airmass.setProperty("value", 1.5)
        self.visibility_airmass.setObjectName("visibility_airmass")
        self.label_15 = QtWidgets.QLabel(POUET)
        self.label_15.setGeometry(QtCore.QRect(980, 510, 61, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(POUET)
        self.label_16.setGeometry(QtCore.QRect(1100, 510, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.visibility_moon_angle = QtWidgets.QSpinBox(POUET)
        self.visibility_moon_angle.setGeometry(QtCore.QRect(1230, 510, 48, 27))
        self.visibility_moon_angle.setMaximum(180)
        self.visibility_moon_angle.setProperty("value", 90)
        self.visibility_moon_angle.setObjectName("visibility_moon_angle")
        self.visibility_plot = QtWidgets.QPushButton(POUET)
        self.visibility_plot.setGeometry(QtCore.QRect(1290, 510, 71, 27))
        self.visibility_plot.setObjectName("visibility_plot")
        self.tabWidget = QtWidgets.QTabWidget(POUET)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 871, 951))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.obs = QtWidgets.QWidget()
        self.obs.setObjectName("obs")
        self.retrieveObs = QtWidgets.QPushButton(self.obs)
        self.retrieveObs.setGeometry(QtCore.QRect(10, 13, 141, 23))
        self.retrieveObs.setObjectName("retrieveObs")
        self.listObs = QtWidgets.QListWidget(self.obs)
        self.listObs.setGeometry(QtCore.QRect(10, 50, 841, 861))
        self.listObs.setObjectName("listObs")
        self.tabWidget.addTab(self.obs, "")
        self.program = QtWidgets.QWidget()
        self.program.setObjectName("program")
        self.label_27 = QtWidgets.QLabel(self.program)
        self.label_27.setGeometry(QtCore.QRect(190, 150, 541, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.tabWidget.addTab(self.program, "")
        self.night = QtWidgets.QWidget()
        self.night.setObjectName("night")
        self.label_24 = QtWidgets.QLabel(self.night)
        self.label_24.setGeometry(QtCore.QRect(160, 100, 541, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.tabWidget.addTab(self.night, "")
        self.weather = QtWidgets.QWidget()
        self.weather.setObjectName("weather")
        self.weather_refresh_now = QtWidgets.QPushButton(self.weather)
        self.weather_refresh_now.setGeometry(QtCore.QRect(20, 170, 111, 27))
        self.weather_refresh_now.setObjectName("weather_refresh_now")
        self.label_9 = QtWidgets.QLabel(self.weather)
        self.label_9.setGeometry(QtCore.QRect(150, 140, 41, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label_5 = QtWidgets.QLabel(self.weather)
        self.label_5.setGeometry(QtCore.QRect(150, 50, 41, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.weather)
        self.label_8.setGeometry(QtCore.QRect(150, 110, 41, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(self.weather)
        self.label_4.setGeometry(QtCore.QRect(190, 20, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.weather)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.weather)
        self.label_6.setGeometry(QtCore.QRect(150, 80, 41, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(self.weather)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.weather)
        self.label_7.setGeometry(QtCore.QRect(20, 80, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.weather)
        self.label_10.setGeometry(QtCore.QRect(20, 110, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.weather)
        self.label_11.setGeometry(QtCore.QRect(20, 140, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.weather, "")
        self.config = QtWidgets.QWidget()
        self.config.setObjectName("config")
        self.config_clouds_analyse = QtWidgets.QCheckBox(self.config)
        self.config_clouds_analyse.setGeometry(QtCore.QRect(10, 120, 131, 22))
        self.config_clouds_analyse.setChecked(True)
        self.config_clouds_analyse.setObjectName("config_clouds_analyse")
        self.config_wind_analyse = QtWidgets.QCheckBox(self.config)
        self.config_wind_analyse.setGeometry(QtCore.QRect(10, 150, 121, 22))
        self.config_wind_analyse.setChecked(True)
        self.config_wind_analyse.setObjectName("config_wind_analyse")
        self.label_18 = QtWidgets.QLabel(self.config)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.toolButton = QtWidgets.QToolButton(self.config)
        self.toolButton.setGeometry(QtCore.QRect(140, 40, 211, 25))
        self.toolButton.setObjectName("toolButton")
        self.label_19 = QtWidgets.QLabel(self.config)
        self.label_19.setGeometry(QtCore.QRect(10, 90, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.config)
        self.label_20.setGeometry(QtCore.QRect(10, 40, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.config_weather_update_every = QtWidgets.QSpinBox(self.config)
        self.config_weather_update_every.setGeometry(QtCore.QRect(170, 180, 48, 27))
        self.config_weather_update_every.setMaximum(30)
        self.config_weather_update_every.setProperty("value", 2)
        self.config_weather_update_every.setObjectName("config_weather_update_every")
        self.label_21 = QtWidgets.QLabel(self.config)
        self.label_21.setGeometry(QtCore.QRect(10, 180, 161, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.line_4 = QtWidgets.QFrame(self.config)
        self.line_4.setGeometry(QtCore.QRect(10, 70, 911, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.config_clouds_auto_update = QtWidgets.QCheckBox(self.config)
        self.config_clouds_auto_update.setGeometry(QtCore.QRect(180, 120, 211, 22))
        self.config_clouds_auto_update.setChecked(True)
        self.config_clouds_auto_update.setObjectName("config_clouds_auto_update")
        self.config_wind_auto_update = QtWidgets.QCheckBox(self.config)
        self.config_wind_auto_update.setGeometry(QtCore.QRect(180, 150, 211, 22))
        self.config_wind_auto_update.setChecked(True)
        self.config_wind_auto_update.setObjectName("config_wind_auto_update")
        self.line_5 = QtWidgets.QFrame(self.config)
        self.line_5.setGeometry(QtCore.QRect(10, 210, 911, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_22 = QtWidgets.QLabel(self.config)
        self.label_22.setGeometry(QtCore.QRect(10, 230, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.config_show_obs_visibility = QtWidgets.QCheckBox(self.config)
        self.config_show_obs_visibility.setGeometry(QtCore.QRect(10, 260, 411, 22))
        self.config_show_obs_visibility.setChecked(True)
        self.config_show_obs_visibility.setObjectName("config_show_obs_visibility")
        self.config_show_obs_allsky = QtWidgets.QCheckBox(self.config)
        self.config_show_obs_allsky.setGeometry(QtCore.QRect(10, 290, 411, 22))
        self.config_show_obs_allsky.setChecked(True)
        self.config_show_obs_allsky.setObjectName("config_show_obs_allsky")
        self.label_25 = QtWidgets.QLabel(self.config)
        self.label_25.setGeometry(QtCore.QRect(10, 890, 391, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.config)
        self.label_26.setGeometry(QtCore.QRect(470, 890, 391, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.tabWidget.addTab(self.config, "")
        self.log = QtWidgets.QWidget()
        self.log.setObjectName("log")
        self.label_28 = QtWidgets.QLabel(self.log)
        self.label_28.setGeometry(QtCore.QRect(130, 150, 541, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.tabWidget.addTab(self.log, "")
        self.update_obs = QtWidgets.QPushButton(POUET)
        self.update_obs.setGeometry(QtCore.QRect(360, 10, 141, 27))
        self.update_obs.setObjectName("update_obs")
        self.clouds_refresh_now = QtWidgets.QPushButton(POUET)
        self.clouds_refresh_now.setGeometry(QtCore.QRect(1060, 10, 101, 27))
        self.clouds_refresh_now.setObjectName("clouds_refresh_now")

        self.retranslateUi(POUET)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(POUET)

    def retranslateUi(self, POUET):
        _translate = QtCore.QCoreApplication.translate
        POUET.setWindowTitle(_translate("POUET", "Pouet"))
        self.label_12.setText(_translate("POUET", "Last update: XX.XX.XXZXX:XX:XX"))
        self.label_13.setText(_translate("POUET", "Current All Sky image"))
        self.label.setText(_translate("POUET", "Date & Time (UTC)"))
        self.config_time.setDisplayFormat(_translate("POUET", "dd.MM.yyyy HH:mm"))
        self.label_14.setText(_translate("POUET", "Visibility"))
        self.label_15.setText(_translate("POUET", "Airmass:"))
        self.label_16.setText(_translate("POUET", "Angle to Moon [°]:"))
        self.visibility_plot.setText(_translate("POUET", "Draw"))
        self.retrieveObs.setText(_translate("POUET", "Load observables list"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.obs), _translate("POUET", "Observations"))
        self.label_27.setText(_translate("POUET", "Here we can select the programs we want to include"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.program), _translate("POUET", "Programs"))
        self.label_24.setText(_translate("POUET", "When does the night begin? When does it end???"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.night), _translate("POUET", "Night"))
        self.weather_refresh_now.setText(_translate("POUET", "Refresh now"))
        self.label_9.setText(_translate("POUET", "XX.X"))
        self.label_5.setText(_translate("POUET", "XX.X"))
        self.label_8.setText(_translate("POUET", "XX.X"))
        self.label_4.setText(_translate("POUET", "Last update: XX.XX.XXZXX:XX:XX"))
        self.label_2.setText(_translate("POUET", "Current weather conditions"))
        self.label_6.setText(_translate("POUET", "XX.X"))
        self.label_3.setText(_translate("POUET", "Wind speed [m/s]:"))
        self.label_7.setText(_translate("POUET", "Wind direction [°]:"))
        self.label_10.setText(_translate("POUET", "Temperature [°C]:"))
        self.label_11.setText(_translate("POUET", "Humidity [%]:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.weather), _translate("POUET", "Weather"))
        self.config_clouds_analyse.setText(_translate("POUET", "Analyse clouds"))
        self.config_wind_analyse.setText(_translate("POUET", "Analyse wind"))
        self.label_18.setText(_translate("POUET", "Observation site"))
        self.toolButton.setText(_translate("POUET", "Load configuration file"))
        self.label_19.setText(_translate("POUET", "Weather analysis"))
        self.label_20.setText(_translate("POUET", "La Silla"))
        self.label_21.setText(_translate("POUET", "Weather update [min]"))
        self.config_clouds_auto_update.setText(_translate("POUET", "Auto-refresh clouds"))
        self.config_wind_auto_update.setText(_translate("POUET", "Auto-refresh wind"))
        self.label_22.setText(_translate("POUET", "Observations"))
        self.config_show_obs_visibility.setText(_translate("POUET", "Show selected objects in visibility tool"))
        self.config_show_obs_allsky.setText(_translate("POUET", "Show selected objects in All Sky image"))
        self.label_25.setText(_translate("POUET", "Written by Thibault Kuntzer and Vivien Bonvin, 2018"))
        self.label_26.setText(_translate("POUET", "https://github.com/vbonvin/POUET"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.config), _translate("POUET", "Configuration"))
        self.label_28.setText(_translate("POUET", "Shows the log files"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log), _translate("POUET", "View logs"))
        self.update_obs.setText(_translate("POUET", "Update"))
        self.clouds_refresh_now.setText(_translate("POUET", "Refresh now"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    POUET = QtWidgets.QDialog()
    ui = Ui_POUET()
    ui.setupUi(POUET)
    POUET.show()
    sys.exit(app.exec_())

