# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_POUET(object):
    def setupUi(self, POUET):
        POUET.setObjectName("POUET")
        POUET.resize(1368, 826)
        self.allSkyUpdateValue = QtWidgets.QLabel(POUET)
        self.allSkyUpdateValue.setGeometry(QtCore.QRect(1150, 10, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.allSkyUpdateValue.setFont(font)
        self.allSkyUpdateValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allSkyUpdateValue.setObjectName("allSkyUpdateValue")
        self.label_13 = QtWidgets.QLabel(POUET)
        self.label_13.setGeometry(QtCore.QRect(900, 10, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label = QtWidgets.QLabel(POUET)
        self.label.setGeometry(QtCore.QRect(20, 10, 131, 31))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.configTime = QtWidgets.QDateTimeEdit(POUET)
        self.configTime.setGeometry(QtCore.QRect(150, 10, 161, 27))
        self.configTime.setAutoFillBackground(False)
        self.configTime.setCalendarPopup(True)
        self.configTime.setObjectName("configTime")
        self.label_14 = QtWidgets.QLabel(POUET)
        self.label_14.setGeometry(QtCore.QRect(900, 410, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.visibilityAirmassValue = QtWidgets.QDoubleSpinBox(POUET)
        self.visibilityAirmassValue.setGeometry(QtCore.QRect(1040, 410, 51, 27))
        self.visibilityAirmassValue.setDecimals(1)
        self.visibilityAirmassValue.setMinimum(1.1)
        self.visibilityAirmassValue.setMaximum(4.0)
        self.visibilityAirmassValue.setSingleStep(0.1)
        self.visibilityAirmassValue.setProperty("value", 1.5)
        self.visibilityAirmassValue.setObjectName("visibilityAirmassValue")
        self.label_15 = QtWidgets.QLabel(POUET)
        self.label_15.setGeometry(QtCore.QRect(980, 410, 61, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(POUET)
        self.label_16.setGeometry(QtCore.QRect(1100, 410, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.visibilityMoonAngleValue = QtWidgets.QSpinBox(POUET)
        self.visibilityMoonAngleValue.setGeometry(QtCore.QRect(1230, 410, 48, 27))
        self.visibilityMoonAngleValue.setMaximum(180)
        self.visibilityMoonAngleValue.setProperty("value", 40)
        self.visibilityMoonAngleValue.setObjectName("visibilityMoonAngleValue")
        self.visibilityDraw = QtWidgets.QPushButton(POUET)
        self.visibilityDraw.setGeometry(QtCore.QRect(1290, 410, 71, 27))
        self.visibilityDraw.setObjectName("visibilityDraw")
        self.tabWidget = QtWidgets.QTabWidget(POUET)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 871, 761))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.obs = QtWidgets.QWidget()
        self.obs.setObjectName("obs")
        self.loadObs = QtWidgets.QPushButton(self.obs)
        self.loadObs.setGeometry(QtCore.QRect(10, 5, 141, 23))
        self.loadObs.setObjectName("loadObs")
        self.listObs = QtWidgets.QTableView(self.obs)
        self.listObs.setGeometry(QtCore.QRect(8, 86, 851, 641))
        self.listObs.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listObs.setDragEnabled(True)
        self.listObs.setAlternatingRowColors(True)
        self.listObs.setShowGrid(True)
        self.listObs.setGridStyle(QtCore.Qt.DashLine)
        self.listObs.setSortingEnabled(True)
        self.listObs.setObjectName("listObs")
        self.listObs.horizontalHeader().setDefaultSectionSize(100)
        self.listObs.horizontalHeader().setMinimumSectionSize(25)
        self.updatePlotObs = QtWidgets.QPushButton(self.obs)
        self.updatePlotObs.setGeometry(QtCore.QRect(320, 5, 151, 23))
        self.updatePlotObs.setObjectName("updatePlotObs")
        self.updateSelectall = QtWidgets.QPushButton(self.obs)
        self.updateSelectall.setGeometry(QtCore.QRect(160, 5, 151, 23))
        self.updateSelectall.setObjectName("updateSelectall")
        self.displaySelectedObs = QtWidgets.QPushButton(self.obs)
        self.displaySelectedObs.setGeometry(QtCore.QRect(690, 34, 151, 23))
        self.displaySelectedObs.setObjectName("displaySelectedObs")
        self.toggleAirmassObs = QtWidgets.QCheckBox(self.obs)
        self.toggleAirmassObs.setGeometry(QtCore.QRect(10, 36, 91, 21))
        self.toggleAirmassObs.setObjectName("toggleAirmassObs")
        self.airmassMaxObs = QtWidgets.QDoubleSpinBox(self.obs)
        self.airmassMaxObs.setGeometry(QtCore.QRect(103, 35, 66, 24))
        self.airmassMaxObs.setMinimum(1.0)
        self.airmassMaxObs.setMaximum(10.0)
        self.airmassMaxObs.setSingleStep(0.1)
        self.airmassMaxObs.setProperty("value", 2.0)
        self.airmassMaxObs.setObjectName("airmassMaxObs")
        self.displayAllObs = QtWidgets.QPushButton(self.obs)
        self.displayAllObs.setGeometry(QtCore.QRect(690, 60, 151, 23))
        self.displayAllObs.setObjectName("displayAllObs")
        self.toggleMoondistObs = QtWidgets.QCheckBox(self.obs)
        self.toggleMoondistObs.setGeometry(QtCore.QRect(180, 36, 101, 21))
        self.toggleMoondistObs.setObjectName("toggleMoondistObs")
        self.moondistMinObs = QtWidgets.QDoubleSpinBox(self.obs)
        self.moondistMinObs.setGeometry(QtCore.QRect(260, 35, 66, 24))
        self.moondistMinObs.setDecimals(0)
        self.moondistMinObs.setMaximum(180.0)
        self.moondistMinObs.setProperty("value", 30.0)
        self.moondistMinObs.setObjectName("moondistMinObs")
        self.sundistMinObs = QtWidgets.QDoubleSpinBox(self.obs)
        self.sundistMinObs.setGeometry(QtCore.QRect(260, 60, 66, 24))
        self.sundistMinObs.setDecimals(0)
        self.sundistMinObs.setMaximum(180.0)
        self.sundistMinObs.setProperty("value", 90.0)
        self.sundistMinObs.setObjectName("sundistMinObs")
        self.toggleSundistObs = QtWidgets.QCheckBox(self.obs)
        self.toggleSundistObs.setGeometry(QtCore.QRect(180, 61, 101, 21))
        self.toggleSundistObs.setObjectName("toggleSundistObs")
        self.toggleUncheckedObs = QtWidgets.QCheckBox(self.obs)
        self.toggleUncheckedObs.setGeometry(QtCore.QRect(680, 0, 91, 21))
        self.toggleUncheckedObs.setObjectName("toggleUncheckedObs")
        self.toggleObservabilityObs = QtWidgets.QCheckBox(self.obs)
        self.toggleObservabilityObs.setGeometry(QtCore.QRect(503, 0, 71, 21))
        self.toggleObservabilityObs.setObjectName("toggleObservabilityObs")
        self.toggleCloudsObs = QtWidgets.QCheckBox(self.obs)
        self.toggleCloudsObs.setGeometry(QtCore.QRect(580, 0, 91, 21))
        self.toggleCloudsObs.setObjectName("toggleCloudsObs")
        self.toggleCheckedObs = QtWidgets.QCheckBox(self.obs)
        self.toggleCheckedObs.setGeometry(QtCore.QRect(780, 0, 81, 21))
        self.toggleCheckedObs.setObjectName("toggleCheckedObs")
        self.alphaMinObs = QtWidgets.QTimeEdit(self.obs)
        self.alphaMinObs.setGeometry(QtCore.QRect(430, 35, 81, 24))
        self.alphaMinObs.setDateTime(QtCore.QDateTime(QtCore.QDate(1999, 9, 29), QtCore.QTime(20, 0, 0)))
        self.alphaMinObs.setMaximumTime(QtCore.QTime(23, 59, 59))
        self.alphaMinObs.setMinimumTime(QtCore.QTime(0, 0, 0))
        self.alphaMinObs.setTimeSpec(QtCore.Qt.UTC)
        self.alphaMinObs.setObjectName("alphaMinObs")
        self.alphaMaxObs = QtWidgets.QTimeEdit(self.obs)
        self.alphaMaxObs.setGeometry(QtCore.QRect(430, 60, 81, 24))
        self.alphaMaxObs.setDateTime(QtCore.QDateTime(QtCore.QDate(1999, 8, 30), QtCore.QTime(19, 59, 59)))
        self.alphaMaxObs.setTimeSpec(QtCore.Qt.UTC)
        self.alphaMaxObs.setObjectName("alphaMaxObs")
        self.toggleAlphaMinObs = QtWidgets.QCheckBox(self.obs)
        self.toggleAlphaMinObs.setGeometry(QtCore.QRect(357, 37, 71, 21))
        self.toggleAlphaMinObs.setObjectName("toggleAlphaMinObs")
        self.toggleAlphaMaxObs = QtWidgets.QCheckBox(self.obs)
        self.toggleAlphaMaxObs.setGeometry(QtCore.QRect(357, 60, 71, 21))
        self.toggleAlphaMaxObs.setObjectName("toggleAlphaMaxObs")
        self.tabWidget.addTab(self.obs, "")
        self.weather = QtWidgets.QWidget()
        self.weather.setObjectName("weather")
        self.weatherDisplayRefresh = QtWidgets.QPushButton(self.weather)
        self.weatherDisplayRefresh.setGeometry(QtCore.QRect(20, 540, 111, 27))
        self.weatherDisplayRefresh.setObjectName("weatherDisplayRefresh")
        self.weatherHumidityValue = QtWidgets.QLabel(self.weather)
        self.weatherHumidityValue.setGeometry(QtCore.QRect(150, 510, 41, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherHumidityValue.setFont(font)
        self.weatherHumidityValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherHumidityValue.setObjectName("weatherHumidityValue")
        self.weatherWindSpeedValue = QtWidgets.QLabel(self.weather)
        self.weatherWindSpeedValue.setGeometry(QtCore.QRect(150, 420, 41, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherWindSpeedValue.setFont(font)
        self.weatherWindSpeedValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherWindSpeedValue.setObjectName("weatherWindSpeedValue")
        self.weatherTemperatureValue = QtWidgets.QLabel(self.weather)
        self.weatherTemperatureValue.setGeometry(QtCore.QRect(150, 480, 41, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherTemperatureValue.setFont(font)
        self.weatherTemperatureValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherTemperatureValue.setObjectName("weatherTemperatureValue")
        self.weatherConditions = QtWidgets.QLabel(self.weather)
        self.weatherConditions.setGeometry(QtCore.QRect(20, 390, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.weatherConditions.setFont(font)
        self.weatherConditions.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherConditions.setObjectName("weatherConditions")
        self.weatherWindDirectionValue = QtWidgets.QLabel(self.weather)
        self.weatherWindDirectionValue.setGeometry(QtCore.QRect(150, 450, 41, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherWindDirectionValue.setFont(font)
        self.weatherWindDirectionValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherWindDirectionValue.setObjectName("weatherWindDirectionValue")
        self.weatherWindSpeed = QtWidgets.QLabel(self.weather)
        self.weatherWindSpeed.setGeometry(QtCore.QRect(20, 420, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherWindSpeed.setFont(font)
        self.weatherWindSpeed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherWindSpeed.setObjectName("weatherWindSpeed")
        self.weatherWindDirection = QtWidgets.QLabel(self.weather)
        self.weatherWindDirection.setGeometry(QtCore.QRect(20, 450, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherWindDirection.setFont(font)
        self.weatherWindDirection.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherWindDirection.setObjectName("weatherWindDirection")
        self.weatherTemperature = QtWidgets.QLabel(self.weather)
        self.weatherTemperature.setGeometry(QtCore.QRect(20, 480, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherTemperature.setFont(font)
        self.weatherTemperature.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherTemperature.setObjectName("weatherTemperature")
        self.weatherHumidity = QtWidgets.QLabel(self.weather)
        self.weatherHumidity.setGeometry(QtCore.QRect(20, 510, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherHumidity.setFont(font)
        self.weatherHumidity.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherHumidity.setObjectName("weatherHumidity")
        self.weatherLastUpdateValue = QtWidgets.QLabel(self.weather)
        self.weatherLastUpdateValue.setGeometry(QtCore.QRect(220, 391, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.weatherLastUpdateValue.setFont(font)
        self.weatherLastUpdateValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherLastUpdateValue.setObjectName("weatherLastUpdateValue")
        self.siteLabel = QtWidgets.QLabel(self.weather)
        self.siteLabel.setGeometry(QtCore.QRect(20, 10, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.siteLabel.setFont(font)
        self.siteLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.siteLabel.setObjectName("siteLabel")
        self.siteLocationValue = QtWidgets.QLabel(self.weather)
        self.siteLocationValue.setGeometry(QtCore.QRect(150, 40, 521, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.siteLocationValue.setFont(font)
        self.siteLocationValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.siteLocationValue.setObjectName("siteLocationValue")
        self.siteLocation = QtWidgets.QLabel(self.weather)
        self.siteLocation.setGeometry(QtCore.QRect(20, 40, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.siteLocation.setFont(font)
        self.siteLocation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.siteLocation.setObjectName("siteLocation")
        self.nightLabel = QtWidgets.QLabel(self.weather)
        self.nightLabel.setGeometry(QtCore.QRect(20, 90, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nightLabel.setFont(font)
        self.nightLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightLabel.setObjectName("nightLabel")
        self.nightStartCivilValue = QtWidgets.QLabel(self.weather)
        self.nightStartCivilValue.setGeometry(QtCore.QRect(150, 120, 181, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightStartCivilValue.setFont(font)
        self.nightStartCivilValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightStartCivilValue.setObjectName("nightStartCivilValue")
        self.nightStartCivil = QtWidgets.QLabel(self.weather)
        self.nightStartCivil.setGeometry(QtCore.QRect(20, 120, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightStartCivil.setFont(font)
        self.nightStartCivil.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightStartCivil.setObjectName("nightStartCivil")
        self.nightEndCivilValue = QtWidgets.QLabel(self.weather)
        self.nightEndCivilValue.setGeometry(QtCore.QRect(550, 120, 181, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightEndCivilValue.setFont(font)
        self.nightEndCivilValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightEndCivilValue.setObjectName("nightEndCivilValue")
        self.nightEndCivil = QtWidgets.QLabel(self.weather)
        self.nightEndCivil.setGeometry(QtCore.QRect(420, 120, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightEndCivil.setFont(font)
        self.nightEndCivil.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightEndCivil.setObjectName("nightEndCivil")
        self.nightStartNauticalValue = QtWidgets.QLabel(self.weather)
        self.nightStartNauticalValue.setGeometry(QtCore.QRect(150, 150, 181, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightStartNauticalValue.setFont(font)
        self.nightStartNauticalValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightStartNauticalValue.setObjectName("nightStartNauticalValue")
        self.nightEndNauticalValue = QtWidgets.QLabel(self.weather)
        self.nightEndNauticalValue.setGeometry(QtCore.QRect(550, 150, 181, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightEndNauticalValue.setFont(font)
        self.nightEndNauticalValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightEndNauticalValue.setObjectName("nightEndNauticalValue")
        self.nightStartNautical = QtWidgets.QLabel(self.weather)
        self.nightStartNautical.setGeometry(QtCore.QRect(20, 150, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightStartNautical.setFont(font)
        self.nightStartNautical.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightStartNautical.setObjectName("nightStartNautical")
        self.nightEndNautical = QtWidgets.QLabel(self.weather)
        self.nightEndNautical.setGeometry(QtCore.QRect(420, 150, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightEndNautical.setFont(font)
        self.nightEndNautical.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightEndNautical.setObjectName("nightEndNautical")
        self.nightStartAstroValue = QtWidgets.QLabel(self.weather)
        self.nightStartAstroValue.setGeometry(QtCore.QRect(150, 180, 181, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightStartAstroValue.setFont(font)
        self.nightStartAstroValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightStartAstroValue.setObjectName("nightStartAstroValue")
        self.nightStartAstro = QtWidgets.QLabel(self.weather)
        self.nightStartAstro.setGeometry(QtCore.QRect(20, 180, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightStartAstro.setFont(font)
        self.nightStartAstro.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightStartAstro.setObjectName("nightStartAstro")
        self.nightEndAstro = QtWidgets.QLabel(self.weather)
        self.nightEndAstro.setGeometry(QtCore.QRect(420, 180, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightEndAstro.setFont(font)
        self.nightEndAstro.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightEndAstro.setObjectName("nightEndAstro")
        self.nightEndAstroValue = QtWidgets.QLabel(self.weather)
        self.nightEndAstroValue.setGeometry(QtCore.QRect(550, 180, 181, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightEndAstroValue.setFont(font)
        self.nightEndAstroValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightEndAstroValue.setObjectName("nightEndAstroValue")
        self.brightLabel = QtWidgets.QLabel(self.weather)
        self.brightLabel.setGeometry(QtCore.QRect(20, 230, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.brightLabel.setFont(font)
        self.brightLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.brightLabel.setObjectName("brightLabel")
        self.sunCoordinatesValues = QtWidgets.QLabel(self.weather)
        self.sunCoordinatesValues.setGeometry(QtCore.QRect(150, 290, 261, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sunCoordinatesValues.setFont(font)
        self.sunCoordinatesValues.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sunCoordinatesValues.setObjectName("sunCoordinatesValues")
        self.sunCoordinates = QtWidgets.QLabel(self.weather)
        self.sunCoordinates.setGeometry(QtCore.QRect(20, 290, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sunCoordinates.setFont(font)
        self.sunCoordinates.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sunCoordinates.setObjectName("sunCoordinates")
        self.sunAltaz = QtWidgets.QLabel(self.weather)
        self.sunAltaz.setGeometry(QtCore.QRect(20, 320, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sunAltaz.setFont(font)
        self.sunAltaz.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sunAltaz.setObjectName("sunAltaz")
        self.sunAltazValue = QtWidgets.QLabel(self.weather)
        self.sunAltazValue.setGeometry(QtCore.QRect(150, 320, 181, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sunAltazValue.setFont(font)
        self.sunAltazValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sunAltazValue.setObjectName("sunAltazValue")
        self.line_8 = QtWidgets.QFrame(self.weather)
        self.line_8.setGeometry(QtCore.QRect(20, 70, 821, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.weather)
        self.line_9.setGeometry(QtCore.QRect(20, 210, 821, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.weather)
        self.line_10.setGeometry(QtCore.QRect(20, 360, 821, 16))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.sunLabel = QtWidgets.QLabel(self.weather)
        self.sunLabel.setGeometry(QtCore.QRect(20, 260, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sunLabel.setFont(font)
        self.sunLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sunLabel.setObjectName("sunLabel")
        self.sunMoon = QtWidgets.QLabel(self.weather)
        self.sunMoon.setGeometry(QtCore.QRect(420, 260, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sunMoon.setFont(font)
        self.sunMoon.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sunMoon.setObjectName("sunMoon")
        self.moonAltazValue = QtWidgets.QLabel(self.weather)
        self.moonAltazValue.setGeometry(QtCore.QRect(550, 320, 181, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.moonAltazValue.setFont(font)
        self.moonAltazValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.moonAltazValue.setObjectName("moonAltazValue")
        self.moonCoordinates = QtWidgets.QLabel(self.weather)
        self.moonCoordinates.setGeometry(QtCore.QRect(420, 290, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.moonCoordinates.setFont(font)
        self.moonCoordinates.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.moonCoordinates.setObjectName("moonCoordinates")
        self.moonAltaz = QtWidgets.QLabel(self.weather)
        self.moonAltaz.setGeometry(QtCore.QRect(420, 320, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.moonAltaz.setFont(font)
        self.moonAltaz.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.moonAltaz.setObjectName("moonAltaz")
        self.moonCoordinatesValues = QtWidgets.QLabel(self.weather)
        self.moonCoordinatesValues.setGeometry(QtCore.QRect(550, 290, 261, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.moonCoordinatesValues.setFont(font)
        self.moonCoordinatesValues.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.moonCoordinatesValues.setObjectName("moonCoordinatesValues")
        self.brightLastUpdateValue = QtWidgets.QLabel(self.weather)
        self.brightLastUpdateValue.setGeometry(QtCore.QRect(130, 231, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.brightLastUpdateValue.setFont(font)
        self.brightLastUpdateValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.brightLastUpdateValue.setObjectName("brightLastUpdateValue")
        self.nightLastUpdateValue = QtWidgets.QLabel(self.weather)
        self.nightLastUpdateValue.setGeometry(QtCore.QRect(69, 92, 331, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.nightLastUpdateValue.setFont(font)
        self.nightLastUpdateValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightLastUpdateValue.setObjectName("nightLastUpdateValue")
        self.tabWidget.addTab(self.weather, "")
        self.config = QtWidgets.QWidget()
        self.config.setObjectName("config")
        self.config_clouds_analyse = QtWidgets.QCheckBox(self.config)
        self.config_clouds_analyse.setEnabled(False)
        self.config_clouds_analyse.setGeometry(QtCore.QRect(10, 120, 131, 22))
        self.config_clouds_analyse.setChecked(True)
        self.config_clouds_analyse.setObjectName("config_clouds_analyse")
        self.config_wind_analyse = QtWidgets.QCheckBox(self.config)
        self.config_wind_analyse.setEnabled(False)
        self.config_wind_analyse.setGeometry(QtCore.QRect(10, 150, 121, 22))
        self.config_wind_analyse.setChecked(True)
        self.config_wind_analyse.setObjectName("config_wind_analyse")
        self.label_18 = QtWidgets.QLabel(self.config)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.toolButton = QtWidgets.QToolButton(self.config)
        self.toolButton.setEnabled(False)
        self.toolButton.setGeometry(QtCore.QRect(140, 40, 211, 25))
        self.toolButton.setObjectName("toolButton")
        self.label_19 = QtWidgets.QLabel(self.config)
        self.label_19.setGeometry(QtCore.QRect(10, 90, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.config)
        self.label_20.setGeometry(QtCore.QRect(10, 40, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.configAutoupdateFreqValue = QtWidgets.QSpinBox(self.config)
        self.configAutoupdateFreqValue.setEnabled(True)
        self.configAutoupdateFreqValue.setGeometry(QtCore.QRect(170, 180, 61, 27))
        self.configAutoupdateFreqValue.setMinimum(1)
        self.configAutoupdateFreqValue.setMaximum(30)
        self.configAutoupdateFreqValue.setSingleStep(1)
        self.configAutoupdateFreqValue.setProperty("value", 2)
        self.configAutoupdateFreqValue.setObjectName("configAutoupdateFreqValue")
        self.label_21 = QtWidgets.QLabel(self.config)
        self.label_21.setGeometry(QtCore.QRect(10, 180, 161, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.line_4 = QtWidgets.QFrame(self.config)
        self.line_4.setGeometry(QtCore.QRect(10, 70, 831, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.configCloudsAutoRefreshValue = QtWidgets.QCheckBox(self.config)
        self.configCloudsAutoRefreshValue.setGeometry(QtCore.QRect(150, 120, 211, 22))
        self.configCloudsAutoRefreshValue.setChecked(True)
        self.configCloudsAutoRefreshValue.setObjectName("configCloudsAutoRefreshValue")
        self.configWindAutoRefreshValue = QtWidgets.QCheckBox(self.config)
        self.configWindAutoRefreshValue.setGeometry(QtCore.QRect(150, 150, 211, 22))
        self.configWindAutoRefreshValue.setChecked(True)
        self.configWindAutoRefreshValue.setObjectName("configWindAutoRefreshValue")
        self.line_5 = QtWidgets.QFrame(self.config)
        self.line_5.setGeometry(QtCore.QRect(10, 240, 831, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_22 = QtWidgets.QLabel(self.config)
        self.label_22.setGeometry(QtCore.QRect(10, 260, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.configShowTargetsVisibilityValue = QtWidgets.QCheckBox(self.config)
        self.configShowTargetsVisibilityValue.setEnabled(True)
        self.configShowTargetsVisibilityValue.setGeometry(QtCore.QRect(10, 290, 411, 22))
        self.configShowTargetsVisibilityValue.setChecked(True)
        self.configShowTargetsVisibilityValue.setObjectName("configShowTargetsVisibilityValue")
        self.configShowTargetsAllSkyValue = QtWidgets.QCheckBox(self.config)
        self.configShowTargetsAllSkyValue.setEnabled(True)
        self.configShowTargetsAllSkyValue.setGeometry(QtCore.QRect(10, 320, 411, 22))
        self.configShowTargetsAllSkyValue.setChecked(True)
        self.configShowTargetsAllSkyValue.setObjectName("configShowTargetsAllSkyValue")
        self.label_25 = QtWidgets.QLabel(self.config)
        self.label_25.setGeometry(QtCore.QRect(10, 700, 441, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.config)
        self.label_26.setGeometry(QtCore.QRect(470, 700, 391, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.configDebugModeValue = QtWidgets.QCheckBox(self.config)
        self.configDebugModeValue.setEnabled(True)
        self.configDebugModeValue.setGeometry(QtCore.QRect(10, 210, 511, 22))
        self.configDebugModeValue.setChecked(False)
        self.configDebugModeValue.setObjectName("configDebugModeValue")
        self.configCloudsShowLayersValue = QtWidgets.QCheckBox(self.config)
        self.configCloudsShowLayersValue.setGeometry(QtCore.QRect(330, 120, 221, 22))
        self.configCloudsShowLayersValue.setChecked(True)
        self.configCloudsShowLayersValue.setObjectName("configCloudsShowLayersValue")
        self.configDoubleClicAirmassValue = QtWidgets.QCheckBox(self.config)
        self.configDoubleClicAirmassValue.setEnabled(True)
        self.configDoubleClicAirmassValue.setGeometry(QtCore.QRect(330, 290, 271, 22))
        self.configDoubleClicAirmassValue.setChecked(True)
        self.configDoubleClicAirmassValue.setObjectName("configDoubleClicAirmassValue")
        self.configDoubleClicSkyChartValue = QtWidgets.QCheckBox(self.config)
        self.configDoubleClicSkyChartValue.setEnabled(True)
        self.configDoubleClicSkyChartValue.setGeometry(QtCore.QRect(330, 320, 431, 22))
        self.configDoubleClicSkyChartValue.setChecked(True)
        self.configDoubleClicSkyChartValue.setObjectName("configDoubleClicSkyChartValue")
        self.tabWidget.addTab(self.config, "")
        self.log = QtWidgets.QWidget()
        self.log.setObjectName("log")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.log)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 841, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget.addTab(self.log, "")
        self.configUpdate = QtWidgets.QPushButton(POUET)
        self.configUpdate.setGeometry(QtCore.QRect(430, 10, 101, 27))
        self.configUpdate.setObjectName("configUpdate")
        self.allSkyRefresh = QtWidgets.QPushButton(POUET)
        self.allSkyRefresh.setGeometry(QtCore.QRect(1057, 7, 101, 27))
        self.allSkyRefresh.setObjectName("allSkyRefresh")
        self.statusFrame = QtWidgets.QFrame(POUET)
        self.statusFrame.setGeometry(QtCore.QRect(540, 10, 341, 51))
        self.statusFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.statusFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statusFrame.setObjectName("statusFrame")
        self.statusLabel = QtWidgets.QLabel(self.statusFrame)
        self.statusLabel.setGeometry(QtCore.QRect(6, 5, 331, 41))
        self.statusLabel.setObjectName("statusLabel")
        self.configTimenow = QtWidgets.QPushButton(POUET)
        self.configTimenow.setGeometry(QtCore.QRect(320, 10, 101, 27))
        self.configTimenow.setObjectName("configTimenow")
        self.allskyView = QtWidgets.QWidget(POUET)
        self.allskyView.setGeometry(QtCore.QRect(900, 40, 461, 351))
        self.allskyView.setObjectName("allskyView")
        self.allSkyUpdateWindValue = QtWidgets.QLabel(POUET)
        self.allSkyUpdateWindValue.setGeometry(QtCore.QRect(1180, 20, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.allSkyUpdateWindValue.setFont(font)
        self.allSkyUpdateWindValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allSkyUpdateWindValue.setObjectName("allSkyUpdateWindValue")
        self.visibilityView = QtWidgets.QWidget(POUET)
        self.visibilityView.setGeometry(QtCore.QRect(900, 440, 461, 381))
        self.visibilityView.setObjectName("visibilityView")
        self.allskyViewLayer = QtWidgets.QWidget(POUET)
        self.allskyViewLayer.setGeometry(QtCore.QRect(900, 40, 461, 351))
        self.allskyViewLayer.setObjectName("allskyViewLayer")
        self.allskyViewLayerTargets = QtWidgets.QWidget(POUET)
        self.allskyViewLayerTargets.setGeometry(QtCore.QRect(900, 40, 461, 351))
        self.allskyViewLayerTargets.setObjectName("allskyViewLayerTargets")
        self.visibilityView.raise_()
        self.allskyView.raise_()
        self.allSkyUpdateValue.raise_()
        self.label_13.raise_()
        self.label.raise_()
        self.configTime.raise_()
        self.label_14.raise_()
        self.visibilityAirmassValue.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.visibilityMoonAngleValue.raise_()
        self.visibilityDraw.raise_()
        self.tabWidget.raise_()
        self.configUpdate.raise_()
        self.allSkyRefresh.raise_()
        self.statusFrame.raise_()
        self.configTimenow.raise_()
        self.allSkyUpdateWindValue.raise_()
        self.allskyViewLayer.raise_()
        self.allskyViewLayerTargets.raise_()

        self.retranslateUi(POUET)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(POUET)

    def retranslateUi(self, POUET):
        _translate = QtCore.QCoreApplication.translate
        POUET.setWindowTitle(_translate("POUET", "Pouet"))
        self.allSkyUpdateValue.setText(_translate("POUET", "XX.XX.XXZXX:XX:XX"))
        self.label_13.setText(_translate("POUET", "Current All Sky image"))
        self.label.setText(_translate("POUET", "Date & Time (UTC)"))
        self.configTime.setDisplayFormat(_translate("POUET", "dd.MM.yyyy HH:mm"))
        self.label_14.setText(_translate("POUET", "Visibility"))
        self.label_15.setText(_translate("POUET", "Airmass:"))
        self.label_16.setText(_translate("POUET", "Angle to Moon [°]:"))
        self.visibilityDraw.setText(_translate("POUET", "Draw"))
        self.loadObs.setText(_translate("POUET", "Load observables list"))
        self.updatePlotObs.setText(_translate("POUET", "Plot selected targets"))
        self.updateSelectall.setText(_translate("POUET", "(De)select all targets"))
        self.displaySelectedObs.setText(_translate("POUET", "Display selected"))
        self.toggleAirmassObs.setText(_translate("POUET", "Airmass <="))
        self.displayAllObs.setText(_translate("POUET", "Display all targets"))
        self.toggleMoondistObs.setText(_translate("POUET", "Moon >"))
        self.toggleSundistObs.setText(_translate("POUET", "Sun   >"))
        self.toggleUncheckedObs.setText(_translate("POUET", "Unchecked"))
        self.toggleObservabilityObs.setText(_translate("POUET", "Obs> 0"))
        self.toggleCloudsObs.setText(_translate("POUET", "Clouds > 0"))
        self.toggleCheckedObs.setText(_translate("POUET", "Checked"))
        self.alphaMinObs.setDisplayFormat(_translate("POUET", "hh:mm:ss"))
        self.alphaMaxObs.setDisplayFormat(_translate("POUET", "hh:mm:ss"))
        self.toggleAlphaMinObs.setText(_translate("POUET", "Alpha >"))
        self.toggleAlphaMaxObs.setText(_translate("POUET", "Alpha <"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.obs), _translate("POUET", "Observations"))
        self.weatherDisplayRefresh.setText(_translate("POUET", "Refresh now"))
        self.weatherHumidityValue.setText(_translate("POUET", "XX.X"))
        self.weatherWindSpeedValue.setText(_translate("POUET", "XX.X"))
        self.weatherTemperatureValue.setText(_translate("POUET", "XX.X"))
        self.weatherConditions.setText(_translate("POUET", "Current weather conditions"))
        self.weatherWindDirectionValue.setText(_translate("POUET", "XX.X"))
        self.weatherWindSpeed.setText(_translate("POUET", "Wind speed [m/s]:"))
        self.weatherWindDirection.setText(_translate("POUET", "Wind direction [°]:"))
        self.weatherTemperature.setText(_translate("POUET", "Temperature [°C]:"))
        self.weatherHumidity.setText(_translate("POUET", "Humidity [%]:"))
        self.weatherLastUpdateValue.setText(_translate("POUET", " XX.XX.XXZXX:XX:XX"))
        self.siteLabel.setText(_translate("POUET", "Station"))
        self.siteLocationValue.setText(_translate("POUET", "XX.X"))
        self.siteLocation.setText(_translate("POUET", "Location:"))
        self.nightLabel.setText(_translate("POUET", "Night"))
        self.nightStartCivilValue.setText(_translate("POUET", "XX.X"))
        self.nightStartCivil.setText(_translate("POUET", "Start (civil):"))
        self.nightEndCivilValue.setText(_translate("POUET", "XX.X"))
        self.nightEndCivil.setText(_translate("POUET", "End (civil):"))
        self.nightStartNauticalValue.setText(_translate("POUET", "XX.X"))
        self.nightEndNauticalValue.setText(_translate("POUET", "XX.X"))
        self.nightStartNautical.setText(_translate("POUET", "Start (nautical):"))
        self.nightEndNautical.setText(_translate("POUET", "End (nautical):"))
        self.nightStartAstroValue.setText(_translate("POUET", "XX.X"))
        self.nightStartAstro.setText(_translate("POUET", "Start (astro):"))
        self.nightEndAstro.setText(_translate("POUET", "End (astro):"))
        self.nightEndAstroValue.setText(_translate("POUET", "XX.X"))
        self.brightLabel.setText(_translate("POUET", "Bright objects"))
        self.sunCoordinatesValues.setText(_translate("POUET", "XX.X"))
        self.sunCoordinates.setText(_translate("POUET", "Coordinates:"))
        self.sunAltaz.setText(_translate("POUET", "Alt [°]/Az [°]:"))
        self.sunAltazValue.setText(_translate("POUET", "XX.X"))
        self.sunLabel.setText(_translate("POUET", "Sun"))
        self.sunMoon.setText(_translate("POUET", "Moon"))
        self.moonAltazValue.setText(_translate("POUET", "XX.X"))
        self.moonCoordinates.setText(_translate("POUET", "Coordinates:"))
        self.moonAltaz.setText(_translate("POUET", "Alt [°]/Az [°]:"))
        self.moonCoordinatesValues.setText(_translate("POUET", "XX.X"))
        self.brightLastUpdateValue.setText(_translate("POUET", "XX.XX.XXXX XX:XX:XX"))
        self.nightLastUpdateValue.setText(_translate("POUET", "XX.XX.XXXX"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.weather), _translate("POUET", "Station"))
        self.config_clouds_analyse.setText(_translate("POUET", "Analyse clouds"))
        self.config_wind_analyse.setText(_translate("POUET", "Analyse wind"))
        self.label_18.setText(_translate("POUET", "Observation site"))
        self.toolButton.setText(_translate("POUET", "Load configuration file"))
        self.label_19.setText(_translate("POUET", "Weather analysis"))
        self.label_20.setText(_translate("POUET", "La Silla"))
        self.label_21.setText(_translate("POUET", "Weather update [min]"))
        self.configCloudsAutoRefreshValue.setText(_translate("POUET", "Auto-refresh clouds"))
        self.configWindAutoRefreshValue.setText(_translate("POUET", "Auto-refresh wind"))
        self.label_22.setText(_translate("POUET", "Observations"))
        self.configShowTargetsVisibilityValue.setText(_translate("POUET", "Show selected objects in visibility tool"))
        self.configShowTargetsAllSkyValue.setText(_translate("POUET", "Show selected objects in All Sky image"))
        self.label_25.setText(_translate("POUET", "Written by Thibault Kuntzer and Vivien Bonvin, 2015-2018"))
        self.label_26.setText(_translate("POUET", "https://github.com/vbonvin/POUET"))
        self.configDebugModeValue.setText(_translate("POUET", "Use local AllSky image and weather report [Debug mode]"))
        self.configCloudsShowLayersValue.setText(_translate("POUET", "Show clouds analysis layers"))
        self.configDoubleClicAirmassValue.setText(_translate("POUET", "On double-clic, show airmass plot"))
        self.configDoubleClicSkyChartValue.setText(_translate("POUET", "On double-clic, show Sky Chart (may require a connection)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.config), _translate("POUET", "Configuration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log), _translate("POUET", "View logs"))
        self.configUpdate.setText(_translate("POUET", "Update"))
        self.allSkyRefresh.setText(_translate("POUET", "Refresh now"))
        self.statusLabel.setText(_translate("POUET", "Current Status"))
        self.configTimenow.setText(_translate("POUET", "Set to now"))
        self.allSkyUpdateWindValue.setText(_translate("POUET", "XX.XX.XXZXX:XX:XX"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    POUET = QtWidgets.QDialog()
    ui = Ui_POUET()
    ui.setupUi(POUET)
    POUET.show()
    sys.exit(app.exec_())

