# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_scalable.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_POUET(object):
    def setupUi(self, POUET):
        POUET.setObjectName("POUET")
        POUET.resize(1253, 824)
        self.centralwidget = QtWidgets.QWidget(POUET)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(600, 400))
        self.tabWidget.setBaseSize(QtCore.QSize(800, 600))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.obs = QtWidgets.QWidget()
        self.obs.setObjectName("obs")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.obs)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.loadObs = QtWidgets.QPushButton(self.obs)
        self.loadObs.setObjectName("loadObs")
        self.horizontalLayout_2.addWidget(self.loadObs)
        self.loadedCatValue = QtWidgets.QLabel(self.obs)
        self.loadedCatValue.setObjectName("loadedCatValue")
        self.horizontalLayout_2.addWidget(self.loadedCatValue)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.updateSelectall = QtWidgets.QPushButton(self.obs)
        self.updateSelectall.setObjectName("updateSelectall")
        self.horizontalLayout_2.addWidget(self.updateSelectall)
        self.displaySelectedObs = QtWidgets.QPushButton(self.obs)
        self.displaySelectedObs.setObjectName("displaySelectedObs")
        self.horizontalLayout_2.addWidget(self.displaySelectedObs)
        self.displayAllObs = QtWidgets.QPushButton(self.obs)
        self.displayAllObs.setObjectName("displayAllObs")
        self.horizontalLayout_2.addWidget(self.displayAllObs)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.updatePlotObs = QtWidgets.QPushButton(self.obs)
        self.updatePlotObs.setObjectName("updatePlotObs")
        self.horizontalLayout_2.addWidget(self.updatePlotObs)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 7)
        self.airmassLayout = QtWidgets.QHBoxLayout()
        self.airmassLayout.setObjectName("airmassLayout")
        self.toggleAirmassObs = QtWidgets.QCheckBox(self.obs)
        self.toggleAirmassObs.setObjectName("toggleAirmassObs")
        self.airmassLayout.addWidget(self.toggleAirmassObs)
        self.airmassMaxObs = QtWidgets.QDoubleSpinBox(self.obs)
        self.airmassMaxObs.setDecimals(1)
        self.airmassMaxObs.setMinimum(1.1)
        self.airmassMaxObs.setMaximum(10.0)
        self.airmassMaxObs.setSingleStep(0.1)
        self.airmassMaxObs.setProperty("value", 2.0)
        self.airmassMaxObs.setObjectName("airmassMaxObs")
        self.airmassLayout.addWidget(self.airmassMaxObs)
        self.gridLayout.addLayout(self.airmassLayout, 1, 0, 1, 1)
        self.moonLayout = QtWidgets.QHBoxLayout()
        self.moonLayout.setObjectName("moonLayout")
        self.toggleMoondistObs = QtWidgets.QCheckBox(self.obs)
        self.toggleMoondistObs.setObjectName("toggleMoondistObs")
        self.moonLayout.addWidget(self.toggleMoondistObs)
        self.moondistMinObs = QtWidgets.QDoubleSpinBox(self.obs)
        self.moondistMinObs.setDecimals(0)
        self.moondistMinObs.setMaximum(180.0)
        self.moondistMinObs.setProperty("value", 30.0)
        self.moondistMinObs.setObjectName("moondistMinObs")
        self.moonLayout.addWidget(self.moondistMinObs)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.moonLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.moonLayout, 1, 1, 1, 2)
        self.sunLayout = QtWidgets.QHBoxLayout()
        self.sunLayout.setObjectName("sunLayout")
        self.toggleSundistObs = QtWidgets.QCheckBox(self.obs)
        self.toggleSundistObs.setObjectName("toggleSundistObs")
        self.sunLayout.addWidget(self.toggleSundistObs)
        self.sundistMinObs = QtWidgets.QDoubleSpinBox(self.obs)
        self.sundistMinObs.setDecimals(0)
        self.sundistMinObs.setMaximum(180.0)
        self.sundistMinObs.setProperty("value", 90.0)
        self.sundistMinObs.setObjectName("sundistMinObs")
        self.sunLayout.addWidget(self.sundistMinObs)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.sunLayout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.sunLayout, 1, 3, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.toggleWindAngleObs = QtWidgets.QCheckBox(self.obs)
        self.toggleWindAngleObs.setObjectName("toggleWindAngleObs")
        self.horizontalLayout_12.addWidget(self.toggleWindAngleObs)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_12, 1, 4, 1, 2)
        self.nameLayout = QtWidgets.QHBoxLayout()
        self.nameLayout.setObjectName("nameLayout")
        self.toggleNameObs = QtWidgets.QCheckBox(self.obs)
        self.toggleNameObs.setObjectName("toggleNameObs")
        self.nameLayout.addWidget(self.toggleNameObs)
        self.nameObs = QtWidgets.QLineEdit(self.obs)
        self.nameObs.setText("")
        self.nameObs.setObjectName("nameObs")
        self.nameLayout.addWidget(self.nameObs)
        self.gridLayout.addLayout(self.nameLayout, 1, 6, 1, 1)
        self.alphaLayout = QtWidgets.QGridLayout()
        self.alphaLayout.setObjectName("alphaLayout")
        self.alphaMinLayout = QtWidgets.QHBoxLayout()
        self.alphaMinLayout.setObjectName("alphaMinLayout")
        self.toggleAlphaMinObs = QtWidgets.QCheckBox(self.obs)
        self.toggleAlphaMinObs.setObjectName("toggleAlphaMinObs")
        self.alphaMinLayout.addWidget(self.toggleAlphaMinObs)
        self.alphaMinObs = QtWidgets.QLineEdit(self.obs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alphaMinObs.sizePolicy().hasHeightForWidth())
        self.alphaMinObs.setSizePolicy(sizePolicy)
        self.alphaMinObs.setObjectName("alphaMinObs")
        self.alphaMinLayout.addWidget(self.alphaMinObs)
        self.alphaLayout.addLayout(self.alphaMinLayout, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.alphaLayout.addItem(spacerItem5, 0, 1, 2, 1)
        self.alphaMaxLayout = QtWidgets.QHBoxLayout()
        self.alphaMaxLayout.setObjectName("alphaMaxLayout")
        self.toggleAlphaMaxObs = QtWidgets.QCheckBox(self.obs)
        self.toggleAlphaMaxObs.setObjectName("toggleAlphaMaxObs")
        self.alphaMaxLayout.addWidget(self.toggleAlphaMaxObs)
        self.alphaMaxObs = QtWidgets.QLineEdit(self.obs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alphaMaxObs.sizePolicy().hasHeightForWidth())
        self.alphaMaxObs.setSizePolicy(sizePolicy)
        self.alphaMaxObs.setObjectName("alphaMaxObs")
        self.alphaMaxLayout.addWidget(self.alphaMaxObs)
        self.alphaLayout.addLayout(self.alphaMaxLayout, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.alphaLayout, 2, 0, 1, 2)
        self.deltaLayout = QtWidgets.QGridLayout()
        self.deltaLayout.setObjectName("deltaLayout")
        self.deltaMinLayout = QtWidgets.QHBoxLayout()
        self.deltaMinLayout.setObjectName("deltaMinLayout")
        self.toggleDeltaMinObs = QtWidgets.QCheckBox(self.obs)
        self.toggleDeltaMinObs.setObjectName("toggleDeltaMinObs")
        self.deltaMinLayout.addWidget(self.toggleDeltaMinObs)
        self.deltaMinObs = QtWidgets.QLineEdit(self.obs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deltaMinObs.sizePolicy().hasHeightForWidth())
        self.deltaMinObs.setSizePolicy(sizePolicy)
        self.deltaMinObs.setObjectName("deltaMinObs")
        self.deltaMinLayout.addWidget(self.deltaMinObs)
        self.deltaLayout.addLayout(self.deltaMinLayout, 0, 0, 1, 1)
        self.deltaMaxLayout = QtWidgets.QHBoxLayout()
        self.deltaMaxLayout.setObjectName("deltaMaxLayout")
        self.toggleDeltaMaxObs = QtWidgets.QCheckBox(self.obs)
        self.toggleDeltaMaxObs.setObjectName("toggleDeltaMaxObs")
        self.deltaMaxLayout.addWidget(self.toggleDeltaMaxObs)
        self.deltaMaxObs = QtWidgets.QLineEdit(self.obs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deltaMaxObs.sizePolicy().hasHeightForWidth())
        self.deltaMaxObs.setSizePolicy(sizePolicy)
        self.deltaMaxObs.setObjectName("deltaMaxObs")
        self.deltaMaxLayout.addWidget(self.deltaMaxObs)
        self.deltaLayout.addLayout(self.deltaMaxLayout, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.deltaLayout.addItem(spacerItem6, 0, 1, 2, 1)
        self.gridLayout.addLayout(self.deltaLayout, 2, 2, 1, 3)
        self.obsCloudSelectLayout = QtWidgets.QVBoxLayout()
        self.obsCloudSelectLayout.setObjectName("obsCloudSelectLayout")
        self.toggleObservabilityObs = QtWidgets.QCheckBox(self.obs)
        self.toggleObservabilityObs.setObjectName("toggleObservabilityObs")
        self.obsCloudSelectLayout.addWidget(self.toggleObservabilityObs)
        self.toggleCloudsObs = QtWidgets.QCheckBox(self.obs)
        self.toggleCloudsObs.setObjectName("toggleCloudsObs")
        self.obsCloudSelectLayout.addWidget(self.toggleCloudsObs)
        self.gridLayout.addLayout(self.obsCloudSelectLayout, 2, 5, 1, 1)
        self.checkSelectLayout = QtWidgets.QVBoxLayout()
        self.checkSelectLayout.setObjectName("checkSelectLayout")
        self.toggleUncheckedObs = QtWidgets.QCheckBox(self.obs)
        self.toggleUncheckedObs.setObjectName("toggleUncheckedObs")
        self.checkSelectLayout.addWidget(self.toggleUncheckedObs)
        self.toggleCheckedObs = QtWidgets.QCheckBox(self.obs)
        self.toggleCheckedObs.setObjectName("toggleCheckedObs")
        self.checkSelectLayout.addWidget(self.toggleCheckedObs)
        self.gridLayout.addLayout(self.checkSelectLayout, 2, 6, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.listObs = QtWidgets.QTableView(self.obs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listObs.sizePolicy().hasHeightForWidth())
        self.listObs.setSizePolicy(sizePolicy)
        self.listObs.setMinimumSize(QtCore.QSize(500, 200))
        self.listObs.setBaseSize(QtCore.QSize(800, 400))
        self.listObs.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listObs.setDragEnabled(True)
        self.listObs.setAlternatingRowColors(True)
        self.listObs.setShowGrid(True)
        self.listObs.setGridStyle(QtCore.Qt.DashLine)
        self.listObs.setSortingEnabled(True)
        self.listObs.setObjectName("listObs")
        self.listObs.horizontalHeader().setDefaultSectionSize(100)
        self.listObs.horizontalHeader().setMinimumSectionSize(25)
        self.verticalLayout_2.addWidget(self.listObs)
        self.saveExportLayout = QtWidgets.QHBoxLayout()
        self.saveExportLayout.setObjectName("saveExportLayout")
        self.saveObs = QtWidgets.QPushButton(self.obs)
        self.saveObs.setObjectName("saveObs")
        self.saveExportLayout.addWidget(self.saveObs)
        self.saveObsLabel = QtWidgets.QLabel(self.obs)
        self.saveObsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.saveObsLabel.setObjectName("saveObsLabel")
        self.saveExportLayout.addWidget(self.saveObsLabel)
        self.saveObsPath = QtWidgets.QLineEdit(self.obs)
        self.saveObsPath.setObjectName("saveObsPath")
        self.saveExportLayout.addWidget(self.saveObsPath)
        self.toggleSaveObsOverwrite = QtWidgets.QCheckBox(self.obs)
        self.toggleSaveObsOverwrite.setChecked(True)
        self.toggleSaveObsOverwrite.setObjectName("toggleSaveObsOverwrite")
        self.saveExportLayout.addWidget(self.toggleSaveObsOverwrite)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.saveExportLayout.addItem(spacerItem7)
        self.printNamesObs = QtWidgets.QPushButton(self.obs)
        self.printNamesObs.setObjectName("printNamesObs")
        self.saveExportLayout.addWidget(self.printNamesObs)
        self.verticalLayout_2.addLayout(self.saveExportLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.obs)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_2.addWidget(self.line_11, 1, 0, 1, 1)
        self.tabWidget.addTab(self.obs, "")
        self.weather = QtWidgets.QWidget()
        self.weather.setObjectName("weather")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.weather)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.siteLabel = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.siteLabel.setFont(font)
        self.siteLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.siteLabel.setObjectName("siteLabel")
        self.verticalLayout_6.addWidget(self.siteLabel)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.siteLocation = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.siteLocation.setFont(font)
        self.siteLocation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.siteLocation.setObjectName("siteLocation")
        self.horizontalLayout_7.addWidget(self.siteLocation)
        self.siteLocationValue = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.siteLocationValue.setFont(font)
        self.siteLocationValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.siteLocationValue.setObjectName("siteLocationValue")
        self.horizontalLayout_7.addWidget(self.siteLocationValue)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.line_8 = QtWidgets.QFrame(self.weather)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_7.addWidget(self.line_8)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.nightLabel = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nightLabel.setFont(font)
        self.nightLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightLabel.setObjectName("nightLabel")
        self.horizontalLayout_6.addWidget(self.nightLabel)
        self.nightLastUpdateValue = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.nightLastUpdateValue.setFont(font)
        self.nightLastUpdateValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightLastUpdateValue.setObjectName("nightLastUpdateValue")
        self.horizontalLayout_6.addWidget(self.nightLastUpdateValue)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.nightStartCivil = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightStartCivil.setFont(font)
        self.nightStartCivil.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightStartCivil.setObjectName("nightStartCivil")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nightStartCivil)
        self.nightStartCivilValue = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightStartCivilValue.setFont(font)
        self.nightStartCivilValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightStartCivilValue.setObjectName("nightStartCivilValue")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nightStartCivilValue)
        self.nightStartNautical = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightStartNautical.setFont(font)
        self.nightStartNautical.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightStartNautical.setObjectName("nightStartNautical")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nightStartNautical)
        self.nightStartNauticalValue = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightStartNauticalValue.setFont(font)
        self.nightStartNauticalValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightStartNauticalValue.setObjectName("nightStartNauticalValue")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nightStartNauticalValue)
        self.nightStartAstro = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightStartAstro.setFont(font)
        self.nightStartAstro.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightStartAstro.setObjectName("nightStartAstro")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.nightStartAstro)
        self.nightStartAstroValue = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightStartAstroValue.setFont(font)
        self.nightStartAstroValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightStartAstroValue.setObjectName("nightStartAstroValue")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nightStartAstroValue)
        self.horizontalLayout_5.addLayout(self.formLayout_4)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.nightEndCivil = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightEndCivil.setFont(font)
        self.nightEndCivil.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightEndCivil.setObjectName("nightEndCivil")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nightEndCivil)
        self.nightEndCivilValue = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightEndCivilValue.setFont(font)
        self.nightEndCivilValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightEndCivilValue.setObjectName("nightEndCivilValue")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nightEndCivilValue)
        self.nightEndNautical = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightEndNautical.setFont(font)
        self.nightEndNautical.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightEndNautical.setObjectName("nightEndNautical")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nightEndNautical)
        self.nightEndNauticalValue = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightEndNauticalValue.setFont(font)
        self.nightEndNauticalValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightEndNauticalValue.setObjectName("nightEndNauticalValue")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nightEndNauticalValue)
        self.nightEndAstro = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightEndAstro.setFont(font)
        self.nightEndAstro.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightEndAstro.setObjectName("nightEndAstro")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.nightEndAstro)
        self.nightEndAstroValue = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightEndAstroValue.setFont(font)
        self.nightEndAstroValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nightEndAstroValue.setObjectName("nightEndAstroValue")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nightEndAstroValue)
        self.horizontalLayout_5.addLayout(self.formLayout_5)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.line_9 = QtWidgets.QFrame(self.weather)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_7.addWidget(self.line_9)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.brightLabel = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.brightLabel.setFont(font)
        self.brightLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.brightLabel.setObjectName("brightLabel")
        self.horizontalLayout_4.addWidget(self.brightLabel)
        self.brightLastUpdateValue = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.brightLastUpdateValue.setFont(font)
        self.brightLastUpdateValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.brightLastUpdateValue.setObjectName("brightLastUpdateValue")
        self.horizontalLayout_4.addWidget(self.brightLastUpdateValue)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem13, 0, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem14, 1, 1, 1, 1)
        self.sunLabel = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sunLabel.setFont(font)
        self.sunLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sunLabel.setObjectName("sunLabel")
        self.gridLayout_4.addWidget(self.sunLabel, 0, 0, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.moonCoordinates = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.moonCoordinates.setFont(font)
        self.moonCoordinates.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.moonCoordinates.setObjectName("moonCoordinates")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.moonCoordinates)
        self.moonCoordinatesValues = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.moonCoordinatesValues.setFont(font)
        self.moonCoordinatesValues.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.moonCoordinatesValues.setObjectName("moonCoordinatesValues")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.moonCoordinatesValues)
        self.moonAltaz = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.moonAltaz.setFont(font)
        self.moonAltaz.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.moonAltaz.setObjectName("moonAltaz")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.moonAltaz)
        self.moonAltazValue = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.moonAltazValue.setFont(font)
        self.moonAltazValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.moonAltazValue.setObjectName("moonAltazValue")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.moonAltazValue)
        self.gridLayout_4.addLayout(self.formLayout_3, 1, 2, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.sunCoordinates = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sunCoordinates.setFont(font)
        self.sunCoordinates.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sunCoordinates.setObjectName("sunCoordinates")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sunCoordinates)
        self.sunCoordinatesValues = QtWidgets.QLabel(self.weather)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sunCoordinatesValues.sizePolicy().hasHeightForWidth())
        self.sunCoordinatesValues.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sunCoordinatesValues.setFont(font)
        self.sunCoordinatesValues.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sunCoordinatesValues.setObjectName("sunCoordinatesValues")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sunCoordinatesValues)
        self.sunAltaz = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sunAltaz.setFont(font)
        self.sunAltaz.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sunAltaz.setObjectName("sunAltaz")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sunAltaz)
        self.sunAltazValue = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sunAltazValue.setFont(font)
        self.sunAltazValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sunAltazValue.setObjectName("sunAltazValue")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sunAltazValue)
        self.gridLayout_4.addLayout(self.formLayout_2, 1, 0, 1, 1)
        self.sunMoon = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sunMoon.setFont(font)
        self.sunMoon.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sunMoon.setObjectName("sunMoon")
        self.gridLayout_4.addWidget(self.sunMoon, 0, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem15, 0, 3, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.line_10 = QtWidgets.QFrame(self.weather)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_7.addWidget(self.line_10)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.weatherConditions = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.weatherConditions.setFont(font)
        self.weatherConditions.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherConditions.setObjectName("weatherConditions")
        self.horizontalLayout_3.addWidget(self.weatherConditions)
        self.weatherLastUpdateValue = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.weatherLastUpdateValue.setFont(font)
        self.weatherLastUpdateValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherLastUpdateValue.setObjectName("weatherLastUpdateValue")
        self.horizontalLayout_3.addWidget(self.weatherLastUpdateValue)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem16)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.weatherWindSpeed = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherWindSpeed.setFont(font)
        self.weatherWindSpeed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherWindSpeed.setObjectName("weatherWindSpeed")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.weatherWindSpeed)
        self.weatherWindSpeedValue = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherWindSpeedValue.setFont(font)
        self.weatherWindSpeedValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherWindSpeedValue.setObjectName("weatherWindSpeedValue")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.weatherWindSpeedValue)
        self.weatherWindDirection = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherWindDirection.setFont(font)
        self.weatherWindDirection.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherWindDirection.setObjectName("weatherWindDirection")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.weatherWindDirection)
        self.weatherWindDirectionValue = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherWindDirectionValue.setFont(font)
        self.weatherWindDirectionValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherWindDirectionValue.setObjectName("weatherWindDirectionValue")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.weatherWindDirectionValue)
        self.weatherTemperature = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherTemperature.setFont(font)
        self.weatherTemperature.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherTemperature.setObjectName("weatherTemperature")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.weatherTemperature)
        self.weatherTemperatureValue = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherTemperatureValue.setFont(font)
        self.weatherTemperatureValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherTemperatureValue.setObjectName("weatherTemperatureValue")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.weatherTemperatureValue)
        self.weatherHumidity = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherHumidity.setFont(font)
        self.weatherHumidity.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherHumidity.setObjectName("weatherHumidity")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.weatherHumidity)
        self.weatherHumidityValue = QtWidgets.QLabel(self.weather)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.weatherHumidityValue.setFont(font)
        self.weatherHumidityValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherHumidityValue.setObjectName("weatherHumidityValue")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.weatherHumidityValue)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.weatherDisplayRefresh = QtWidgets.QPushButton(self.weather)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weatherDisplayRefresh.sizePolicy().hasHeightForWidth())
        self.weatherDisplayRefresh.setSizePolicy(sizePolicy)
        self.weatherDisplayRefresh.setObjectName("weatherDisplayRefresh")
        self.verticalLayout_3.addWidget(self.weatherDisplayRefresh)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.gridLayout_5.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.weather, "")
        self.config = QtWidgets.QWidget()
        self.config.setObjectName("config")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.config)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_18 = QtWidgets.QLabel(self.config)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_9.addWidget(self.label_18)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_20 = QtWidgets.QLabel(self.config)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_9.addWidget(self.label_20)
        self.toolButton = QtWidgets.QToolButton(self.config)
        self.toolButton.setEnabled(False)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_9.addWidget(self.toolButton)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem17)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.verticalLayout_11.addLayout(self.verticalLayout_9)
        self.line_4 = QtWidgets.QFrame(self.config)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_11.addWidget(self.line_4)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_19 = QtWidgets.QLabel(self.config)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_10.addWidget(self.label_19)
        self.configCloudsAnalysis = QtWidgets.QCheckBox(self.config)
        self.configCloudsAnalysis.setEnabled(True)
        self.configCloudsAnalysis.setChecked(True)
        self.configCloudsAnalysis.setObjectName("configCloudsAnalysis")
        self.verticalLayout_10.addWidget(self.configCloudsAnalysis)
        self.config_wind_analyse = QtWidgets.QCheckBox(self.config)
        self.config_wind_analyse.setEnabled(False)
        self.config_wind_analyse.setChecked(True)
        self.config_wind_analyse.setObjectName("config_wind_analyse")
        self.verticalLayout_10.addWidget(self.config_wind_analyse)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.configCloudsAutoRefreshValue = QtWidgets.QCheckBox(self.config)
        self.configCloudsAutoRefreshValue.setChecked(True)
        self.configCloudsAutoRefreshValue.setObjectName("configCloudsAutoRefreshValue")
        self.horizontalLayout_10.addWidget(self.configCloudsAutoRefreshValue)
        self.configCloudsShowLayersValue = QtWidgets.QCheckBox(self.config)
        self.configCloudsShowLayersValue.setChecked(True)
        self.configCloudsShowLayersValue.setObjectName("configCloudsShowLayersValue")
        self.horizontalLayout_10.addWidget(self.configCloudsShowLayersValue)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem18)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.configWindAutoRefreshValue = QtWidgets.QCheckBox(self.config)
        self.configWindAutoRefreshValue.setChecked(True)
        self.configWindAutoRefreshValue.setObjectName("configWindAutoRefreshValue")
        self.verticalLayout_10.addWidget(self.configWindAutoRefreshValue)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_21 = QtWidgets.QLabel(self.config)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_11.addWidget(self.label_21)
        self.configAutoupdateFreqValue = QtWidgets.QSpinBox(self.config)
        self.configAutoupdateFreqValue.setEnabled(True)
        self.configAutoupdateFreqValue.setMinimum(1)
        self.configAutoupdateFreqValue.setMaximum(30)
        self.configAutoupdateFreqValue.setSingleStep(1)
        self.configAutoupdateFreqValue.setProperty("value", 2)
        self.configAutoupdateFreqValue.setObjectName("configAutoupdateFreqValue")
        self.horizontalLayout_11.addWidget(self.configAutoupdateFreqValue)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem19)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.configDebugModeValue = QtWidgets.QCheckBox(self.config)
        self.configDebugModeValue.setEnabled(True)
        self.configDebugModeValue.setChecked(False)
        self.configDebugModeValue.setObjectName("configDebugModeValue")
        self.verticalLayout_10.addWidget(self.configDebugModeValue)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.line_5 = QtWidgets.QFrame(self.config)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_11.addWidget(self.line_5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_22 = QtWidgets.QLabel(self.config)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_8.addWidget(self.label_22)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.configShowTargetsVisibilityValue = QtWidgets.QCheckBox(self.config)
        self.configShowTargetsVisibilityValue.setEnabled(True)
        self.configShowTargetsVisibilityValue.setChecked(True)
        self.configShowTargetsVisibilityValue.setObjectName("configShowTargetsVisibilityValue")
        self.gridLayout_6.addWidget(self.configShowTargetsVisibilityValue, 0, 0, 1, 1)
        self.configShowTargetsAllSkyValue = QtWidgets.QCheckBox(self.config)
        self.configShowTargetsAllSkyValue.setEnabled(True)
        self.configShowTargetsAllSkyValue.setChecked(True)
        self.configShowTargetsAllSkyValue.setObjectName("configShowTargetsAllSkyValue")
        self.gridLayout_6.addWidget(self.configShowTargetsAllSkyValue, 1, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_6)
        self.verticalLayout_11.addLayout(self.verticalLayout_8)
        self.gridLayout_7.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_25 = QtWidgets.QLabel(self.config)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_8.addWidget(self.label_25, 0, QtCore.Qt.AlignHCenter)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem20)
        self.label_26 = QtWidgets.QLabel(self.config)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_8.addWidget(self.label_26)
        self.gridLayout_7.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem21, 1, 0, 1, 1)
        self.tabWidget.addTab(self.config, "")
        self.log = QtWidgets.QWidget()
        self.log.setObjectName("log")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.log)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 721, 671))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget.addTab(self.log, "")
        self.gridLayout_3.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.allSkyVisibilityLayout = QtWidgets.QVBoxLayout()
        self.allSkyVisibilityLayout.setObjectName("allSkyVisibilityLayout")
        self.allSkyUpdateLayout = QtWidgets.QHBoxLayout()
        self.allSkyUpdateLayout.setSpacing(6)
        self.allSkyUpdateLayout.setObjectName("allSkyUpdateLayout")
        self.allSkyUpdateLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allSkyUpdateLabel.sizePolicy().hasHeightForWidth())
        self.allSkyUpdateLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.allSkyUpdateLabel.setFont(font)
        self.allSkyUpdateLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.allSkyUpdateLabel.setObjectName("allSkyUpdateLabel")
        self.allSkyUpdateLayout.addWidget(self.allSkyUpdateLabel)
        self.allSkyRefresh = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allSkyRefresh.sizePolicy().hasHeightForWidth())
        self.allSkyRefresh.setSizePolicy(sizePolicy)
        self.allSkyRefresh.setObjectName("allSkyRefresh")
        self.allSkyUpdateLayout.addWidget(self.allSkyRefresh)
        self.allSkyUpdateValueLayout = QtWidgets.QVBoxLayout()
        self.allSkyUpdateValueLayout.setObjectName("allSkyUpdateValueLayout")
        self.allSkyUpdateValue = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allSkyUpdateValue.sizePolicy().hasHeightForWidth())
        self.allSkyUpdateValue.setSizePolicy(sizePolicy)
        self.allSkyUpdateValue.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.allSkyUpdateValue.setFont(font)
        self.allSkyUpdateValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allSkyUpdateValue.setObjectName("allSkyUpdateValue")
        self.allSkyUpdateValueLayout.addWidget(self.allSkyUpdateValue)
        self.allSkyUpdateWindValue = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allSkyUpdateWindValue.sizePolicy().hasHeightForWidth())
        self.allSkyUpdateWindValue.setSizePolicy(sizePolicy)
        self.allSkyUpdateWindValue.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.allSkyUpdateWindValue.setFont(font)
        self.allSkyUpdateWindValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allSkyUpdateWindValue.setObjectName("allSkyUpdateWindValue")
        self.allSkyUpdateValueLayout.addWidget(self.allSkyUpdateWindValue)
        self.allSkyUpdateLayout.addLayout(self.allSkyUpdateValueLayout)
        self.allSkyVisibilityLayout.addLayout(self.allSkyUpdateLayout)
        self.allskyViewContainer = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allskyViewContainer.sizePolicy().hasHeightForWidth())
        self.allskyViewContainer.setSizePolicy(sizePolicy)
        self.allskyViewContainer.setMinimumSize(QtCore.QSize(466, 350))
        self.allskyViewContainer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.allskyViewContainer.setBaseSize(QtCore.QSize(300, 300))
        self.allskyViewContainer.setObjectName("allskyViewContainer")
        self.allskyViewLayer = QtWidgets.QWidget(self.allskyViewContainer)
        self.allskyViewLayer.setGeometry(QtCore.QRect(0, 0, 466, 350))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allskyViewLayer.sizePolicy().hasHeightForWidth())
        self.allskyViewLayer.setSizePolicy(sizePolicy)
        self.allskyViewLayer.setMinimumSize(QtCore.QSize(250, 250))
        self.allskyViewLayer.setBaseSize(QtCore.QSize(300, 300))
        self.allskyViewLayer.setObjectName("allskyViewLayer")
        self.allskyViewLayerTargets = QtWidgets.QWidget(self.allskyViewContainer)
        self.allskyViewLayerTargets.setGeometry(QtCore.QRect(0, 0, 466, 350))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allskyViewLayerTargets.sizePolicy().hasHeightForWidth())
        self.allskyViewLayerTargets.setSizePolicy(sizePolicy)
        self.allskyViewLayerTargets.setMinimumSize(QtCore.QSize(250, 350))
        self.allskyViewLayerTargets.setBaseSize(QtCore.QSize(300, 300))
        self.allskyViewLayerTargets.setObjectName("allskyViewLayerTargets")
        self.allskyView = QtWidgets.QWidget(self.allskyViewContainer)
        self.allskyView.setGeometry(QtCore.QRect(0, 0, 466, 350))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allskyView.sizePolicy().hasHeightForWidth())
        self.allskyView.setSizePolicy(sizePolicy)
        self.allskyView.setMinimumSize(QtCore.QSize(250, 250))
        self.allskyView.setBaseSize(QtCore.QSize(300, 300))
        self.allskyView.setObjectName("allskyView")
        self.allskyView.raise_()
        self.allskyViewLayer.raise_()
        self.allskyViewLayerTargets.raise_()
        self.allSkyVisibilityLayout.addWidget(self.allskyViewContainer)
        self.visibilityLabelsLayout = QtWidgets.QHBoxLayout()
        self.visibilityLabelsLayout.setObjectName("visibilityLabelsLayout")
        self.visibilityLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visibilityLabel.sizePolicy().hasHeightForWidth())
        self.visibilityLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.visibilityLabel.setFont(font)
        self.visibilityLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.visibilityLabel.setObjectName("visibilityLabel")
        self.visibilityLabelsLayout.addWidget(self.visibilityLabel)
        self.visibilityAirmassLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visibilityAirmassLabel.sizePolicy().hasHeightForWidth())
        self.visibilityAirmassLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.visibilityAirmassLabel.setFont(font)
        self.visibilityAirmassLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.visibilityAirmassLabel.setObjectName("visibilityAirmassLabel")
        self.visibilityLabelsLayout.addWidget(self.visibilityAirmassLabel)
        self.visibilityAirmassValue = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.visibilityAirmassValue.setDecimals(1)
        self.visibilityAirmassValue.setMinimum(1.1)
        self.visibilityAirmassValue.setMaximum(4.0)
        self.visibilityAirmassValue.setSingleStep(0.1)
        self.visibilityAirmassValue.setProperty("value", 1.5)
        self.visibilityAirmassValue.setObjectName("visibilityAirmassValue")
        self.visibilityLabelsLayout.addWidget(self.visibilityAirmassValue)
        self.visibilityMoonAngleLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visibilityMoonAngleLabel.sizePolicy().hasHeightForWidth())
        self.visibilityMoonAngleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.visibilityMoonAngleLabel.setFont(font)
        self.visibilityMoonAngleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.visibilityMoonAngleLabel.setObjectName("visibilityMoonAngleLabel")
        self.visibilityLabelsLayout.addWidget(self.visibilityMoonAngleLabel)
        self.visibilityMoonAngleValue = QtWidgets.QSpinBox(self.centralwidget)
        self.visibilityMoonAngleValue.setMaximum(180)
        self.visibilityMoonAngleValue.setProperty("value", 40)
        self.visibilityMoonAngleValue.setObjectName("visibilityMoonAngleValue")
        self.visibilityLabelsLayout.addWidget(self.visibilityMoonAngleValue)
        self.visibilityDraw = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visibilityDraw.sizePolicy().hasHeightForWidth())
        self.visibilityDraw.setSizePolicy(sizePolicy)
        self.visibilityDraw.setObjectName("visibilityDraw")
        self.visibilityLabelsLayout.addWidget(self.visibilityDraw)
        self.allSkyVisibilityLayout.addLayout(self.visibilityLabelsLayout)
        self.visibilityView = QtWidgets.QWidget(self.centralwidget)
        self.visibilityView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visibilityView.sizePolicy().hasHeightForWidth())
        self.visibilityView.setSizePolicy(sizePolicy)
        self.visibilityView.setMinimumSize(QtCore.QSize(250, 350))
        self.visibilityView.setBaseSize(QtCore.QSize(300, 300))
        self.visibilityView.setObjectName("visibilityView")
        self.allSkyVisibilityLayout.addWidget(self.visibilityView)
        self.gridLayout_3.addLayout(self.allSkyVisibilityLayout, 0, 1, 2, 1)
        self.dateStatusLayout = QtWidgets.QHBoxLayout()
        self.dateStatusLayout.setObjectName("dateStatusLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 23))
        self.label.setBaseSize(QtCore.QSize(0, 23))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.dateStatusLayout.addWidget(self.label)
        self.configTime = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.configTime.setAutoFillBackground(False)
        self.configTime.setCalendarPopup(True)
        self.configTime.setObjectName("configTime")
        self.dateStatusLayout.addWidget(self.configTime)
        self.configTimenow = QtWidgets.QPushButton(self.centralwidget)
        self.configTimenow.setObjectName("configTimenow")
        self.dateStatusLayout.addWidget(self.configTimenow)
        self.configUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.configUpdate.setObjectName("configUpdate")
        self.dateStatusLayout.addWidget(self.configUpdate)
        self.statusFrame = QtWidgets.QFrame(self.centralwidget)
        self.statusFrame.setBaseSize(QtCore.QSize(340, 50))
        self.statusFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.statusFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statusFrame.setObjectName("statusFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.statusFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.statusLabel = QtWidgets.QLabel(self.statusFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        self.statusLabel.setMinimumSize(QtCore.QSize(200, 30))
        self.statusLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.statusLabel.setBaseSize(QtCore.QSize(340, 50))
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout.addWidget(self.statusLabel)
        self.dateStatusLayout.addWidget(self.statusFrame)
        self.gridLayout_3.addLayout(self.dateStatusLayout, 0, 0, 1, 1)
        POUET.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(POUET)
        self.statusbar.setObjectName("statusbar")
        POUET.setStatusBar(self.statusbar)

        self.retranslateUi(POUET)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(POUET)

    def retranslateUi(self, POUET):
        _translate = QtCore.QCoreApplication.translate
        POUET.setWindowTitle(_translate("POUET", "POUET"))
        self.loadObs.setText(_translate("POUET", "Load catalog"))
        self.loadedCatValue.setText(_translate("POUET", "No catalog loaded"))
        self.updateSelectall.setText(_translate("POUET", "(De)select all "))
        self.displaySelectedObs.setText(_translate("POUET", "Sort"))
        self.displayAllObs.setText(_translate("POUET", "Reset list"))
        self.updatePlotObs.setText(_translate("POUET", "Display selected"))
        self.toggleAirmassObs.setText(_translate("POUET", "Airmass <="))
        self.toggleMoondistObs.setText(_translate("POUET", "Moon >"))
        self.toggleSundistObs.setText(_translate("POUET", "Sun   >"))
        self.toggleWindAngleObs.setText(_translate("POUET", "WindAngle"))
        self.toggleNameObs.setText(_translate("POUET", "Name"))
        self.toggleAlphaMinObs.setText(_translate("POUET", "Alpha >"))
        self.alphaMinObs.setText(_translate("POUET", "00:00:00"))
        self.toggleAlphaMaxObs.setText(_translate("POUET", "Alpha <"))
        self.alphaMaxObs.setText(_translate("POUET", "23:59:59"))
        self.toggleDeltaMinObs.setText(_translate("POUET", "Delta >"))
        self.deltaMinObs.setText(_translate("POUET", "-90:00:00"))
        self.toggleDeltaMaxObs.setText(_translate("POUET", "Delta <"))
        self.deltaMaxObs.setText(_translate("POUET", "90:00:00"))
        self.toggleObservabilityObs.setText(_translate("POUET", "Obs> 0"))
        self.toggleCloudsObs.setText(_translate("POUET", "Clouds > 0"))
        self.toggleUncheckedObs.setText(_translate("POUET", "Unselected"))
        self.toggleCheckedObs.setText(_translate("POUET", "Selected"))
        self.saveObs.setText(_translate("POUET", "Export selected"))
        self.saveObsLabel.setText(_translate("POUET", "Save path:"))
        self.saveObsPath.setText(_translate("POUET", "cats/temp.pouet"))
        self.toggleSaveObsOverwrite.setText(_translate("POUET", "Overwrite"))
        self.printNamesObs.setText(_translate("POUET", "Show selected names"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.obs), _translate("POUET", "Observations"))
        self.siteLabel.setText(_translate("POUET", "Station"))
        self.siteLocation.setText(_translate("POUET", "Location:"))
        self.siteLocationValue.setText(_translate("POUET", "XX.X"))
        self.nightLabel.setText(_translate("POUET", "Night"))
        self.nightLastUpdateValue.setText(_translate("POUET", "XX.XX.XXXX"))
        self.nightStartCivil.setText(_translate("POUET", "Start (civil):"))
        self.nightStartCivilValue.setText(_translate("POUET", "XX.X"))
        self.nightStartNautical.setText(_translate("POUET", "Start (nautical):"))
        self.nightStartNauticalValue.setText(_translate("POUET", "XX.X"))
        self.nightStartAstro.setText(_translate("POUET", "Start (astro):"))
        self.nightStartAstroValue.setText(_translate("POUET", "XX.X"))
        self.nightEndCivil.setText(_translate("POUET", "End (civil):"))
        self.nightEndCivilValue.setText(_translate("POUET", "XX.X"))
        self.nightEndNautical.setText(_translate("POUET", "End (nautical):"))
        self.nightEndNauticalValue.setText(_translate("POUET", "XX.X"))
        self.nightEndAstro.setText(_translate("POUET", "End (astro):"))
        self.nightEndAstroValue.setText(_translate("POUET", "XX.X"))
        self.brightLabel.setText(_translate("POUET", "Bright objects"))
        self.brightLastUpdateValue.setText(_translate("POUET", "XX.XX.XXXX XX:XX:XX"))
        self.sunLabel.setText(_translate("POUET", "Sun"))
        self.moonCoordinates.setText(_translate("POUET", "Coordinates:"))
        self.moonCoordinatesValues.setText(_translate("POUET", "XX.X"))
        self.moonAltaz.setText(_translate("POUET", "Alt [°]/Az [°]:"))
        self.moonAltazValue.setText(_translate("POUET", "XX.X"))
        self.sunCoordinates.setText(_translate("POUET", "Coordinates:"))
        self.sunCoordinatesValues.setText(_translate("POUET", "XX.X"))
        self.sunAltaz.setText(_translate("POUET", "Alt [°]/Az [°]:"))
        self.sunAltazValue.setText(_translate("POUET", "XX.X"))
        self.sunMoon.setText(_translate("POUET", "Moon"))
        self.weatherConditions.setText(_translate("POUET", "Current weather conditions"))
        self.weatherLastUpdateValue.setText(_translate("POUET", " XX.XX.XXZXX:XX:XX"))
        self.weatherWindSpeed.setText(_translate("POUET", "Wind speed [m/s]:"))
        self.weatherWindSpeedValue.setText(_translate("POUET", "XX.X"))
        self.weatherWindDirection.setText(_translate("POUET", "Wind direction [°]:"))
        self.weatherWindDirectionValue.setText(_translate("POUET", "XX.X"))
        self.weatherTemperature.setText(_translate("POUET", "Temperature [°C]:"))
        self.weatherTemperatureValue.setText(_translate("POUET", "XX.X"))
        self.weatherHumidity.setText(_translate("POUET", "Humidity [%]:"))
        self.weatherHumidityValue.setText(_translate("POUET", "XX.X"))
        self.weatherDisplayRefresh.setText(_translate("POUET", "Refresh now"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.weather), _translate("POUET", "Station"))
        self.label_18.setText(_translate("POUET", "Observation site"))
        self.label_20.setText(_translate("POUET", "La Silla"))
        self.toolButton.setText(_translate("POUET", "Load configuration file"))
        self.label_19.setText(_translate("POUET", "Weather analysis"))
        self.configCloudsAnalysis.setText(_translate("POUET", "Take clouds into account for observability estimation"))
        self.config_wind_analyse.setText(_translate("POUET", "Analyse wind"))
        self.configCloudsAutoRefreshValue.setText(_translate("POUET", "Auto-refresh clouds"))
        self.configCloudsShowLayersValue.setText(_translate("POUET", "Show clouds analysis layers"))
        self.configWindAutoRefreshValue.setText(_translate("POUET", "Auto-refresh wind"))
        self.label_21.setText(_translate("POUET", "Weather update [min]"))
        self.configDebugModeValue.setText(_translate("POUET", "Use local AllSky image and weather report [Debug mode]"))
        self.label_22.setText(_translate("POUET", "Observations"))
        self.configShowTargetsVisibilityValue.setText(_translate("POUET", "Show selected objects in visibility tool"))
        self.configShowTargetsAllSkyValue.setText(_translate("POUET", "Show selected objects in All Sky image"))
        self.label_25.setText(_translate("POUET", "Written by Thibault Kuntzer and Vivien Bonvin, 2015-2018"))
        self.label_26.setText(_translate("POUET", "https://github.com/vbonvin/POUET"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.config), _translate("POUET", "Configuration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log), _translate("POUET", "View logs"))
        self.allSkyUpdateLabel.setText(_translate("POUET", "Current All Sky image"))
        self.allSkyRefresh.setText(_translate("POUET", "Refresh now"))
        self.allSkyUpdateValue.setText(_translate("POUET", "XX.XX.XXZXX:XX:XX"))
        self.allSkyUpdateWindValue.setText(_translate("POUET", "XX.XX.XXZXX:XX:XX"))
        self.visibilityLabel.setText(_translate("POUET", "Visibility"))
        self.visibilityAirmassLabel.setText(_translate("POUET", "Airmass:"))
        self.visibilityMoonAngleLabel.setText(_translate("POUET", "Angle to Moon [°]:"))
        self.visibilityDraw.setText(_translate("POUET", "Draw"))
        self.label.setText(_translate("POUET", "Date & Time (UTC)"))
        self.configTime.setDisplayFormat(_translate("POUET", "dd.MM.yyyy HH:mm"))
        self.configTimenow.setText(_translate("POUET", "Set to now"))
        self.configUpdate.setText(_translate("POUET", "Update"))
        self.statusLabel.setText(_translate("POUET", "Current Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    POUET = QtWidgets.QMainWindow()
    ui = Ui_POUET()
    ui.setupUi(POUET)
    POUET.show()
    sys.exit(app.exec_())

